// controllers/aiAgentController.js
const { getChatModel, getModel } = require('../config/gemini');
const projectController = require('./projectcontroller');
const taskController = require('./taskcontroller');
const userController = require('./usercontroller');
const submissionController = require('./tasksubmissioncontroller');

// Helper to get current user
const getCurrentUser = (req) => {
    return req.user || null;
};

// Generate project description
const generateProjectDescription = async (projectName, domain) => {

    try {

        const model = getModel();

        const prompt = `

You are generating a professional project description for a project management system.

Project Name:

"${projectName}"

Project Domain:

"${domain || 'Not specified'}"

Generate a clear and professional project description.

Requirements:

- Write 2-3 sentences.

- Explain what the project is intended to achieve.

- Mention the main purpose or objectives.

- Mention the expected outcome or value.

- Use the project name and domain to make the description specific.

- Do not invent highly specific features that were not implied by the project name or domain.

- Do not mention that the description was generated by AI.

- Do not use Markdown.

- Do not use headings, bullet points, or quotation marks.

- Return ONLY the project description.

Example style:

"This project focuses on developing an intelligent AI-powered platform designed to streamline project management and improve team productivity. It aims to provide efficient tools for managing projects, tasks, and collaboration while delivering better visibility into project progress and outcomes."

`;

        const result = await model.generateContent(prompt);

        const generatedDescription = result.response.text().trim();

        if (!generatedDescription) {

            throw new Error('AI returned an empty project description');

        }

        return generatedDescription;

    } catch (error) {

        console.error('❌ Error generating project description:', error);

        // Safe fallback if Gemini fails

        return domain

            ? `The ${projectName} project focuses on delivering solutions within the ${domain} domain. It aims to achieve its key objectives efficiently while providing meaningful value and measurable outcomes.`

            : `The ${projectName} project focuses on delivering a practical solution to achieve its intended objectives. It aims to provide meaningful value while supporting efficient project execution and successful outcomes.`;

    }

};

exports.generateProjectDescription = generateProjectDescription;

const generateTaskDescription = async (taskName) => {
    try {
        const model = getModel();

        const prompt = `
You are generating a professional task description for a project management system.

Task Name:
"${taskName}"

Generate a useful task description based only on the task name.

Requirements:
- Write 1-2 clear sentences.
- Explain what needs to be completed.
- Make the description practical and actionable.
- Keep it relevant to the task name.
- Do not invent unnecessary project-specific information.
- Do not mention that the description was generated by AI.
- Do not use Markdown.
- Do not use headings or bullet points.
- Return ONLY the task description.

Example:

Task Name:
"Design Frontend Page"

Description:
"Design and implement the required frontend page with a clear, responsive, and user-friendly interface that meets the project's UI requirements."
`;

        const result = await model.generateContent(prompt);

        const generatedDescription = result.response.text().trim();

        if (!generatedDescription) {
            throw new Error('AI returned an empty task description');
        }

        return generatedDescription;

    } catch (error) {
        console.error('❌ Error generating task description:', error);

        return `Complete the "${taskName}" task according to the project requirements and ensure that the expected work is properly implemented.`;
    }
};

exports.generateTaskDescription = generateTaskDescription;

// Helper to safely execute controller functions
const safeExecute = async (controllerFn, req, res) => {
    try {
        const result = await controllerFn(req, res);
        return result;
    } catch (error) {
        console.error('Controller execution error:', error);
        return {
            success: false,
            error: error.message || 'Operation failed'
        };
    }
};

// Function definitions with better error handling
const functions = {
    createProject: async (params, user) => {
        const { name, domain, aboutTitle, aboutDescription, startDate, deadline, priority } = params;
        
        console.log('🔍 createProject called with:', { name, domain, priority, userRole: user?.role });
        
        // Check permissions
        if (!['Executive Manager', 'System Administrator'].includes(user?.role)) {
            console.log('❌ Permission denied. User role:', user?.role);
            return { 
                success: false, 
                error: `Only Executive Managers and System Administrators can create projects. Your role: ${user?.role || 'Unknown'}`
            };
        }

        if (!name) {
            console.log('❌ Project name is missing');
            return { success: false, error: 'Project name is required.' };
        }

        if (!domain || !String(domain).trim()) {
            return {
                success: false,
                error: 'Project domain is required.'
            };
        }

        if (!startDate) {
            return {
                success: false,
                error: 'Project start date is required.'
            };
        }
        
        if (!deadline) {
            return {
                success: false,
                error: 'Project deadline is required.'
            };
        }
        
        const start = new Date(startDate);
        const end = new Date(deadline);
        
        if (
            Number.isNaN(start.getTime()) ||
            Number.isNaN(end.getTime())
        ) {
            return {
                success: false,
                error: 'Invalid project date format. Use YYYY-MM-DD.'
            };
        }
        
        if (end < start) {
            return {
                success: false,
                error: 'Project deadline cannot be earlier than the start date.'
            };
        }

        // Generate description if not provided
        let description = aboutDescription;
        if (!description && name) {
            console.log('📝 Generating description for:', name);
            try {
                description = await generateProjectDescription(name, domain);
                console.log('✅ Description generated successfully');
            } catch (error) {
                console.error('❌ Failed to generate description:', error);
                description = `A project focused on ${name} to deliver value.`;
            }
        }

        // Prepare request
        const req = {
            body: {
                name,
                domain: domain || null,
                aboutTitle: aboutTitle || name,
                aboutDescription: description,
                startDate: startDate || null,
                deadline: deadline || null,
                priority: priority || 'Medium'
            },
            user: user
        };

        console.log('📤 Sending to projectController.createProject');

        const res = {
            status: (code) => ({
                json: (data) => {
                    console.log(`📥 Response status ${code}:`, data);
                    return { status: code, data };
                },
                send: (data) => {
                    console.log('📥 Response send:', data);
                    return { data };
                }
            })
        };

        try {
            const result = await projectController.createProject(req, res);
            console.log('✅ Project creation result:', result);
            
            // Check if result has data property
            if (result && result.data) {
                return result.data;
            }
            return result || { success: true, message: 'Project created successfully' };
        } catch (error) {
            console.error('❌ Project creation error:', error);
            return { 
                success: false, 
                error: error.message || 'Failed to create project',
                details: error.stack
            };
        }
    },

    getProjects: async (params, user) => {
        console.log('🔍 getProjects called for user:', user?.id);
        
        const req = { user };
        const res = {
            status: (code) => ({
                json: (data) => {
                    console.log(`📥 Projects response status ${code}`);
                    return { status: code, data };
                },
                send: (data) => {
                    console.log('📥 Projects response send');
                    return { data };
                }
            })
        };

        try {
            const result = await projectController.getProjects(req, res);
            console.log('✅ Projects fetched successfully');
            return result.data || result || { success: true, projects: [] };
        } catch (error) {
            console.error('❌ Get projects error:', error);
            return { 
                success: false, 
                error: error.message || 'Failed to get projects' 
            };
        }
    },

   createTask: async (params, user) => {

    const {
        projectId,
        projectName,
        name,
        description,
        status,
        priority,
        assigneeId,
        startDate,
        dueDate
    } = params;

    console.log('🔍 createTask called:', {
        projectId,
        projectName,
        name,
        startDate,
        dueDate,
        userRole: user?.role
    });

    // =====================================================
    // PERMISSION CHECK
    // =====================================================

    if (
        ![
            'Executive Manager',
            'System Administrator',
            'Project Manager'
        ].includes(user?.role)
    ) {
        return {
            success: false,
            error: 'Only Project Managers and above can create tasks.'
        };
    }

    // =====================================================
    // REQUIRED TASK NAME
    // =====================================================

    if (!name || !String(name).trim()) {
        return {
            success: false,
            error: 'Task name is required.'
        };
    }

    // =====================================================
    // REQUIRED DATES
    // =====================================================

    if (!startDate) {
        return {
            success: false,
            error: 'Task start date is required.'
        };
    }

    if (!dueDate) {
        return {
            success: false,
            error: 'Task due date is required.'
        };
    }

    // =====================================================
    // DATE VALIDATION
    // =====================================================

    if (startDate && dueDate) {

        const start = new Date(startDate);
        const due = new Date(dueDate);

        if (
            Number.isNaN(start.getTime()) ||
            Number.isNaN(due.getTime())
        ) {
            return {
                success: false,
                error: 'Invalid task date format. Use YYYY-MM-DD.'
            };
        }

        if (due < start) {
            return {
                success: false,
                error: 'Task due date cannot be earlier than the start date.'
            };
        }
    }

    // =====================================================
    // RESOLVE PROJECT
    // =====================================================

    let resolvedProjectId = projectId || null;
    let resolvedProjectName = projectName || null;

    /*
     * If project ID is provided, trust it.
     *
     * If project name is provided instead, search for the
     * exact project name.
     */

    if (!resolvedProjectId && projectName) {

        console.log(
            `🔎 Searching project by name: "${projectName}"`
        );

        const projectsReq = {
            user
        };

        const projectsRes = {
            status: (code) => ({
                json: (data) => ({
                    status: code,
                    data
                }),

                send: (data) => ({
                    data
                })
            })
        };

        try {

            const projectsResult =
                await projectController.getProjects(
                    projectsReq,
                    projectsRes
                );

            const projectsData =
                projectsResult?.data || projectsResult;

            console.log(
                '📦 Projects returned:',
                projectsData
            );

            const projects =
                Array.isArray(projectsData)
                    ? projectsData
                    : projectsData?.projects || [];

            // Normalize project name
            const normalizedProjectName =
                String(projectName)
                    .trim()
                    .toLowerCase();

            // Exact case-insensitive match
            const matchedProjects =
                projects.filter((project) => {

                    const currentName =
                        String(
                            project.name ||
                            project.projectName ||
                            ''
                        )
                            .trim()
                            .toLowerCase();

                    return currentName === normalizedProjectName;
                });

            console.log(
                `🔎 Found ${matchedProjects.length} project(s) matching "${projectName}"`
            );

            // =================================================
            // NO PROJECT FOUND
            // =================================================

            if (matchedProjects.length === 0) {

                return {
                    success: false,

                    requiresProjectSelection: true,

                    projectName,

                    error:
                        `No project named "${projectName}" was found. ` +
                        `Please provide the exact project name.`
                };
            }

            // =================================================
            // MULTIPLE PROJECTS FOUND
            // =================================================

            if (matchedProjects.length > 1) {

                const projectOptions =
                    matchedProjects.map((project) => ({
                        id: project.id,
                        name:
                            project.name ||
                            project.projectName,
                        status:
                            project.status || null
                    }));

                return {

                    success: false,

                    requiresProjectSelection: true,

                    multipleProjects: true,

                    projectName,

                    projects: projectOptions,

                    error:
                        `Multiple projects named "${projectName}" were found. ` +
                        `Please provide the project ID.`
                };
            }

            // =================================================
            // EXACTLY ONE PROJECT FOUND
            // =================================================

            resolvedProjectId =
                matchedProjects[0].id;

            resolvedProjectName =
                matchedProjects[0].name ||
                matchedProjects[0].projectName ||
                projectName;

            console.log(
                `✅ Project resolved: "${resolvedProjectName}" → ID ${resolvedProjectId}`
            );

        } catch (error) {

            console.error(
                '❌ Project name resolution error:',
                error
            );

            return {

                success: false,

                error:
                    'Unable to find the project. Please try again or provide the project ID.'
            };
        }
    }

    // =====================================================
    // PROJECT REQUIRED
    // =====================================================

    if (!resolvedProjectId) {

        return {
            success: false,

            requiresProjectSelection: true,

            error:
                'Please provide a project name or project ID.'
        };
    }

    // =====================================================
    // GENERATE TASK DESCRIPTION IF MISSING
    // =====================================================

    let finalDescription = description;

    if (
        !finalDescription ||
        !String(finalDescription).trim()
    ) {

        console.log(
            `📝 No task description provided. Generating description for: "${name}"`
        );

        finalDescription =
            await generateTaskDescription(name);

        console.log(
            '✅ Task description generated successfully'
        );
    }

    // =====================================================
    // PREPARE REQUEST FOR TASK CONTROLLER
    // =====================================================

    const req = {

        params: {
            projectId: resolvedProjectId
        },

        body: {

            name: String(name).trim(),

            /*
             * IMPORTANT:
             * Use finalDescription here.
             *
             * If user supplied a description:
             *     → their exact description is preserved.
             *
             * If user did not supply one:
             *     → generated description is used.
             */
            description: finalDescription,

            status: status || 'To Do',

            priority: priority || 'Medium',

            assigneeId: assigneeId || null,

            startDate,

            dueDate
        },

        user
    };

    console.log(
        '📤 Sending task to taskController.createTask:',
        {
            projectId: resolvedProjectId,
            projectName: resolvedProjectName,
            name,
            startDate,
            dueDate,
            priority: priority || 'Medium',
            descriptionGenerated: !description
        }
    );

    // =====================================================
    // MOCK RESPONSE OBJECT
    // =====================================================

    const res = {

        status: (code) => ({

            json: (data) => ({
                status: code,
                data
            }),

            send: (data) => ({
                data
            })
        })
    };

    // =====================================================
    // CREATE TASK
    // =====================================================

    try {

        const result =
            await taskController.createTask(
                req,
                res
            );

        const taskResult =
            result?.data || result;

        console.log(
            '✅ Task creation result:',
            taskResult
        );

        return {

            ...taskResult,

            projectId: resolvedProjectId,

            projectName: resolvedProjectName
        };

    } catch (error) {

        console.error(
            '❌ Create task error:',
            error
        );

        return {

            success: false,

            error:
                error.message ||
                'Failed to create task'
        };
    }
},

    assignProject: async (params, user) => {
        const { projectId, managerId } = params;

        console.log('🔍 assignProject called:', { projectId, managerId, userRole: user?.role });

        if (!['Executive Manager', 'System Administrator', 'Project Manager'].includes(user?.role)) {
            return { success: false, error: 'Only managers can assign projects.' };
        }

        if (!projectId || !managerId) {
            return { success: false, error: 'Project ID and Manager ID are required.' };
        }

        const req = {
            params: { projectId },
            body: { managerId },
            user: user
        };

        const res = {
            status: (code) => ({
                json: (data) => ({ status: code, data }),
                send: (data) => ({ data })
            })
        };

        try {
            const result = await projectController.assignProject(req, res);
            return result.data || result;
        } catch (error) {
            console.error('❌ Assign project error:', error);
            return { success: false, error: error.message || 'Failed to assign project' };
        }
    },

    updateTaskStatus: async (params, user) => {
        const { taskId, status } = params;

        if (!['Executive Manager', 'System Administrator', 'Project Manager'].includes(user?.role)) {
            return { success: false, error: 'Only Project Managers and above can update task status.' };
        }

        if (!taskId || !status) {
            return { success: false, error: 'Task ID and status are required.' };
        }

        const req = {
            params: { taskId },
            body: { status },
            user: user
        };

        const res = {
            status: (code) => ({
                json: (data) => ({ status: code, data }),
                send: (data) => ({ data })
            })
        };

        try {
            const result = await taskController.updateTaskStatus(req, res);
            return result.data || result;
        } catch (error) {
            console.error('❌ Update task status error:', error);
            return { success: false, error: error.message || 'Failed to update task status' };
        }
    },

    deleteTask: async (params, user) => {
        const { taskId } = params;

        if (!['Executive Manager', 'System Administrator', 'Project Manager'].includes(user?.role)) {
            return { success: false, error: 'Only Project Managers and above can delete tasks.' };
        }

        if (!taskId) {
            return { success: false, error: 'Task ID is required.' };
        }

        const req = {
            params: { taskId },
            user: user
        };

        const res = {
            status: (code) => ({
                json: (data) => ({ status: code, data }),
                send: (data) => ({ data })
            })
        };

        try {
            const result = await taskController.deleteTask(req, res);
            return result.data || result;
        } catch (error) {
            console.error('❌ Delete task error:', error);
            return { success: false, error: error.message || 'Failed to delete task' };
        }
    },

    submitWork: async (params, user) => {
        const { taskId, link, description } = params;

        if (user?.role !== 'Member') {
            return { success: false, error: 'Only Members can submit work for tasks.' };
        }

        if (!taskId || !link) {
            return { success: false, error: 'Task ID and link are required.' };
        }

        const req = {
            params: { taskId },
            body: { link, description: description || null },
            user: user
        };

        const res = {
            status: (code) => ({
                json: (data) => ({ status: code, data }),
                send: (data) => ({ data })
            })
        };

        try {
            const result = await submissionController.addSubmission(req, res);
            return result.data || result;
        } catch (error) {
            console.error('❌ Submit work error:', error);
            return { success: false, error: error.message || 'Failed to submit work' };
        }
    },

    getProjectManagers: async (params, user) => {
        const req = { user };
        const res = {
            status: (code) => ({
                json: (data) => ({ status: code, data }),
                send: (data) => ({ data })
            })
        };

        try {
            const result = await projectController.getProjectManagers(req, res);
            return result.data || result;
        } catch (error) {
            console.error('❌ Get project managers error:', error);
            return { success: false, error: error.message || 'Failed to get project managers' };
        }
    },

    getUsers: async (params, user) => {
        const req = { user };
        const res = {
            status: (code) => ({
                json: (data) => ({ status: code, data }),
                send: (data) => ({ data })
            })
        };

        try {
            const result = await userController.getUsers(req, res);
            return result.data || result;
        } catch (error) {
            console.error('❌ Get users error:', error);
            return { success: false, error: error.message || 'Failed to get users' };
        }
    }
};

// Parse AI response for function calls
const parseAIResponse = (response) => {
    console.log('🔍 Parsing AI response:', response?.substring(0, 200) + '...');
    
    const functionRegex = /\[FUNCTION:(\w+)\]({[^}]*})/g;
    const match = functionRegex.exec(response);

    if (match) {
        try {
            const functionName = match[1];
            const arguments = JSON.parse(match[2]);
            console.log(`✅ Parsed function: ${functionName}`, arguments);
            return {
                function_call: { name: functionName, arguments: arguments },
                response: response.replace(match[0], '').trim()
            };
        } catch (error) {
            console.error('❌ Failed to parse function call:', error);
            console.error('Raw match:', match[0]);
        }
    }

    console.log('ℹ️ No function call found in response');
    return { function_call: null, response };
};

// Generate final response
const generateFinalResponse = async (functionName, result, user) => {
    try {
        const model = getModel();
        const prompt = `
        A user executed the function "${functionName}".
        Result: ${JSON.stringify(result, null, 2)}
        
        Generate a brief, professional response summarizing what happened.
        If successful, confirm with details.
        If error, explain clearly.
        Keep it to 2-3 sentences.
        `;

        const aiResult = await model.generateContent(prompt);
        return aiResult.response.text().trim();
    } catch (error) {
        console.error('Error generating final response:', error);
        return `Executed ${functionName}. Check the results for details.`;
    }
};

// Main handler
exports.handleAIAgent = async (req, res) => {
    try {
        const { message, conversationHistory = [] } = req.body;
        const user = getCurrentUser(req);

        console.log('=== 🤖 AI Agent Request ===');
        console.log('User:', user?.id, user?.role);
        console.log('Message:', message?.substring(0, 100) + '...');

        if (!message) {
            return res.status(400).json({ success: false, error: 'Message is required' });
        }

        // Check API key
        const apiKey = process.env.GOOGLE_API_KEY || process.env.GOOGLE_AI_API_KEY;
        if (!apiKey) {
            console.error('❌ Google AI API key is not configured');
            return res.status(500).json({
                success: false,
                error: 'Google AI API key is not configured. Please add GOOGLE_API_KEY to your environment variables.'
            });
        }
        console.log('✅ API key configured');

        // Get chat model
        let model;
        try {
            model = getChatModel();
            console.log('✅ Chat model initialized');
        } catch (error) {
            console.error('❌ Model init error:', error);
            return res.status(500).json({
                success: false,
                error: 'Failed to initialize AI model. Please check your API key.'
            });
        }

        // Build the prompt with system instructions
      const systemInstruction = `
You are an AI assistant for a Project Management System.

You can help users manage projects, tasks, assignments, and submissions.

Your job is to understand natural-language requests, collect required information when necessary, and call the appropriate backend function only when enough information is available.

IMPORTANT:
You must never invent IDs, dates, project names, user IDs, manager IDs, descriptions, or other user-provided information.

=========================================================
AVAILABLE FUNCTIONS
=========================================================

1. createProject

Parameters:
{
  "name": "string",
  "domain": "string|null",
  "aboutTitle": "string|null",
  "aboutDescription": "string|null",
  "startDate": "YYYY-MM-DD|null",
  "deadline": "YYYY-MM-DD|null",
  "priority": "Low|Medium|High"
}

Purpose:
Creates a new project.

Required information before calling:
- name
- domain
- startDate
- deadline

Optional:
- aboutTitle
- aboutDescription
- priority

Project description behavior:
- If the user provides a project description, pass that description as aboutDescription.
- Preserve the user's description. Do not replace it with an AI-generated description.
- If the user does not provide a project description, send aboutDescription as null or omit it.
- The backend will generate the project description automatically when it is missing.

Project priority behavior:
- If the user specifies Low, Medium, or High, use that exact priority.
- If the user does not specify a priority, use "Medium".

IMPORTANT:
Do NOT call createProject if domain, startDate, or deadline is missing.
Instead, ask the user for all missing required information.

---------------------------------------------------------

2. getProjects

Parameters:
{}

Purpose:
Gets projects available to the current user.

---------------------------------------------------------

3. createTask

Parameters:
{
  "projectName": "string|null",
  "projectId": "string|null",
  "name": "string",
  "description": "string|null",
  "status": "string|null",
  "priority": "Low|Medium|High",
  "assigneeId": "string|null",
  "startDate": "YYYY-MM-DD|null",
  "dueDate": "YYYY-MM-DD|null"
}

Purpose:
Creates a task inside a project.

Required information before calling:
- task name
- projectName OR projectId
- startDate
- dueDate

Optional:
- description
- status
- priority
- assigneeId

Task description behavior:
- If the user provides a task description, pass it exactly as provided.
- Do not replace a user-provided description with an AI-generated description.
- If the user does not provide a description, do NOT ask the user for one.
- Send description as null or omit it.
- The backend will automatically generate a professional task description from the task name.

Task priority behavior:
- If the user specifies Low, Medium, or High, use that exact priority.
- If the user does not specify a priority, use "Medium".

Task status behavior:
- If the user specifies a status, preserve it.
- If the user does not specify a status, send null or omit it.
- The backend will apply its default task status.

---------------------------------------------------------

4. updateTaskStatus

Parameters:
{
  "taskId": "string",
  "status": "string"
}

Purpose:
Updates the status of an existing task.

Required:
- taskId
- status

Never invent a task ID.

---------------------------------------------------------

5. deleteTask

Parameters:
{
  "taskId": "string"
}

Purpose:
Deletes an existing task.

Required:
- taskId

Never invent a task ID.

---------------------------------------------------------

6. assignProject

Parameters:
{
  "projectId": "string",
  "managerId": "string"
}

Purpose:
Assigns a project to a project manager.

Required:
- projectId
- managerId

Never invent IDs.

---------------------------------------------------------

7. submitWork

Parameters:
{
  "taskId": "string",
  "link": "string",
  "description": "string|null"
}

Purpose:
Allows a Member to submit work for a task using a link.

Required:
- taskId
- link

Optional:
- description

Never invent task IDs or work links.

---------------------------------------------------------

8. getProjectManagers

Parameters:
{}

Purpose:
Gets available project managers.

---------------------------------------------------------

9. getUsers

Parameters:
{}

Purpose:
Gets users available to the current user.

=========================================================
GENERAL FUNCTION CALL RULES
=========================================================

When the user asks you to perform an action, return EXACTLY:

[FUNCTION:functionName]{"param":"value"}

IMPORTANT:

- Return valid JSON.
- Use double quotes for JSON keys and string values.
- Do NOT use Markdown.
- Do NOT wrap JSON in code fences.
- Do NOT add text before the [FUNCTION:...] marker.
- Do NOT add text after the JSON.
- Do not invent missing IDs.
- Do not invent dates.
- Do not invent project names.
- Do not invent user IDs.
- Do not invent manager IDs.
- Do not invent information that the user has not provided.
- Always respect the user's role and backend permission rules.
- Use exactly Low, Medium, or High for priority.
- Use dates in YYYY-MM-DD format when the user has supplied a date.
- If the user gives a natural-language date such as "September 15", convert it to YYYY-MM-DD using the current year only when the year is clearly implied by the conversation context.
- If the year cannot be determined safely, ask the user for the year instead of inventing it.
- Do not call a function when required information is missing.
- When required information is missing, ask the user for it instead.
- If multiple required fields are missing, ask for all of them together.
- Do not ask again for information the user has already provided.
- Optional information should not block the function unless explicitly marked as required.

=========================================================
PROJECT CREATION RULES
=========================================================

A project requires:

1. Project name
2. Project domain
3. Project start date
4. Project deadline

Project description is NOT required from the user.

If the user provides a description:
- Use the exact user-provided description.

If the user does not provide a description:
- Do not ask for a description.
- Allow the backend to generate it automatically.

Priority is optional:
- If missing, use "Medium".

Examples of project creation requests:

User:
Create a project called AI Chatbot

Assistant:
Do NOT call a function.

Ask:
Please provide the project domain, start date, and deadline.

---------------------------------------------------------

User:
Create a project called AI Chatbot with domain Generative AI

Assistant:
Do NOT call a function.

Ask:
Please provide the project start date and deadline.

---------------------------------------------------------

User:
Create AI Chatbot. Domain is Generative AI, start date is September 10, deadline is October 30.

Assistant:
[FUNCTION:createProject]{"name":"AI Chatbot","domain":"Generative AI","startDate":"2026-09-10","deadline":"2026-10-30","priority":"Medium"}

---------------------------------------------------------

User:
Create a high priority project called AI Chatbot. Domain Generative AI. Start September 10 and deadline October 30.

Assistant:
[FUNCTION:createProject]{"name":"AI Chatbot","domain":"Generative AI","startDate":"2026-09-10","deadline":"2026-10-30","priority":"High"}

---------------------------------------------------------

User:
Create AI Chatbot. It is a Generative AI project that provides an intelligent project management assistant. Start September 10 and finish October 30.

Assistant:
[FUNCTION:createProject]{"name":"AI Chatbot","domain":"Generative AI","aboutDescription":"It is a Generative AI project that provides an intelligent project management assistant.","startDate":"2026-09-10","deadline":"2026-10-30","priority":"Medium"}

IMPORTANT:
If the user provides a project description, use it.
If the user does not provide a project description, do not ask for it.

=========================================================
TASK CREATION RULES
=========================================================

A task requires:

1. Task name
2. Project name OR project ID
3. Start date
4. Due date

Task description is NOT required from the user.

If the user provides a task description:
- Use the exact description provided.

If the user does not provide a task description:
- Do NOT ask for it.
- The backend will automatically generate the description from the task name.

Priority is optional:
- If missing, use "Medium".

Status is optional:
- If missing, allow the backend to apply its default.

---------------------------------------------------------
PROJECT IDENTIFICATION
---------------------------------------------------------

Users should normally be allowed to identify a project by its name.

Understand project references such as:

"for AI Chatbot"
"in AI Chatbot"
"under AI Chatbot"
"inside AI Chatbot"
"inside the AI Chatbot project"
"for the AI Chatbot project"
"add this to AI Chatbot"
"create this task in AI Chatbot"
"add a task to the AI Chatbot project"
"create a task under the project called AI Chatbot"

All of these should result in:

"projectName": "AI Chatbot"

Do not require the user to know the project ID.

Only use projectId when:
- The user explicitly provides a project ID.
- OR the user selects a project ID after the backend reports multiple projects with the same name.

---------------------------------------------------------
TASK CREATION EXAMPLES
---------------------------------------------------------

User:
Create a task "Design Frontend Page" for AI Chatbot project

Assistant:
Do NOT call a function yet.

Ask:
What start date and due date should I use for this task?

---------------------------------------------------------

User:
Create a task "Design Frontend Page" for AI Chatbot project. Start September 10 and due September 15.

Assistant:
[FUNCTION:createTask]{"projectName":"AI Chatbot","name":"Design Frontend Page","startDate":"2026-09-10","dueDate":"2026-09-15","priority":"Medium"}

---------------------------------------------------------

User:
Create a high priority task "Design Frontend Page" for AI Chatbot. Start September 10 and due September 15.

Assistant:
[FUNCTION:createTask]{"projectName":"AI Chatbot","name":"Design Frontend Page","startDate":"2026-09-10","dueDate":"2026-09-15","priority":"High"}

---------------------------------------------------------

User:
Create "Build Login API" in Sales Management System. Start September 12 and due September 20.

Assistant:
[FUNCTION:createTask]{"projectName":"Sales Management System","name":"Build Login API","startDate":"2026-09-12","dueDate":"2026-09-20","priority":"Medium"}

---------------------------------------------------------

User:
Add a task called "Fix authentication" under Employee Portal. Start September 11 and due September 18.

Assistant:
[FUNCTION:createTask]{"projectName":"Employee Portal","name":"Fix authentication","startDate":"2026-09-11","dueDate":"2026-09-18","priority":"Medium"}

---------------------------------------------------------

User:
Create a task "Database Design" for Mobile Application. Start September 12 and due September 25. The description is "Design the complete PostgreSQL database structure."

Assistant:
[FUNCTION:createTask]{"projectName":"Mobile Application","name":"Database Design","description":"Design the complete PostgreSQL database structure.","startDate":"2026-09-12","dueDate":"2026-09-25","priority":"Medium"}

---------------------------------------------------------
MISSING TASK INFORMATION
---------------------------------------------------------

User:
Create a task Design Frontend Page for AI Chatbot

Assistant:
Do NOT call createTask.

Ask:
Please provide the task start date and due date.

---------------------------------------------------------

User:
Create a task Design Frontend Page for AI Chatbot with start date September 10

Assistant:
Do NOT call createTask.

Ask:
Please provide the task due date.

---------------------------------------------------------

User:
Create a task Design Frontend Page

Assistant:
Do NOT call createTask.

Ask:
Please provide the project name, start date, and due date.

---------------------------------------------------------

User:
Create a task Design Frontend Page for AI Chatbot. Due September 20.

Assistant:
Do NOT call createTask.

Ask:
Please provide the task start date.

=========================================================
DUPLICATE PROJECT NAME HANDLING
=========================================================

If the user specifies a project name instead of a project ID, use projectName.

The backend will search for matching projects.

If exactly one project matches:
- The backend will automatically resolve the project ID.
- Continue with task creation.

If multiple projects have the same name:
- The backend will return multiple matching projects and ask for a project ID.
- Do not invent or select an ID yourself.
- Ask the user which project ID they want to use.
- Preserve all previously collected task information.

Example:

User:
Create Design Login Page for AI Chatbot. Start September 10 and due September 15.

If multiple projects exist, the backend may return:

AI Chatbot — ID 15
AI Chatbot — ID 27

Assistant:
I found multiple projects named "AI Chatbot". Please provide the project ID you want to use.

User:
27

Then use:

[FUNCTION:createTask]{"projectId":"27","name":"Design Login Page","startDate":"2026-09-10","dueDate":"2026-09-15","priority":"Medium"}

Do not lose the task name or dates while waiting for the project ID.

=========================================================
PROJECT ID RULES
=========================================================

If the user explicitly provides a project ID:

User:
Create task Design Dashboard for project ID 27. Start September 10 and due September 15.

Assistant:
[FUNCTION:createTask]{"projectId":"27","name":"Design Dashboard","startDate":"2026-09-10","dueDate":"2026-09-15","priority":"Medium"}

If the user provides both project name and project ID:

User:
Create Design Dashboard for AI Chatbot project ID 27. Start September 10 and due September 15.

Assistant:
[FUNCTION:createTask]{"projectId":"27","projectName":"AI Chatbot","name":"Design Dashboard","startDate":"2026-09-10","dueDate":"2026-09-15","priority":"Medium"}

When both are supplied, trust the explicitly provided project ID.

=========================================================
NATURAL LANGUAGE UNDERSTANDING
=========================================================

Users may phrase requests in many different ways.

You must understand variations such as:

"Create a task called Design Frontend Page for AI Chatbot"

"Add Design Frontend Page to AI Chatbot"

"I need a Design Frontend Page task in AI Chatbot"

"Make a task named Design Frontend Page under AI Chatbot"

"Put Design Frontend Page in the AI Chatbot project"

"Add a task for AI Chatbot called Design Frontend Page"

"Create Design Frontend Page inside the AI Chatbot project"

"Can you add Design Frontend Page to the AI Chatbot project?"

All should be interpreted as:

task name = Design Frontend Page
project name = AI Chatbot

Then check whether start date and due date are available.

=========================================================
DESCRIPTION RULES
=========================================================

PROJECT:

If user says:

"Create AI Chatbot. Domain Generative AI. Start September 10. Deadline October 30."

Do NOT ask:
"What is the description?"

Instead call createProject without aboutDescription and allow the backend to generate it.

If user says:

"Create AI Chatbot. Domain Generative AI. Description: An AI assistant for managing projects. Start September 10. Deadline October 30."

Pass:

"aboutDescription": "An AI assistant for managing projects."

TASK:

If user says:

"Create Design Frontend Page for AI Chatbot. Start September 10. Due September 15."

Do NOT ask for task description.

Call createTask without description and allow the backend to generate it.

If user says:

"Create Design Frontend Page for AI Chatbot. Description: Build a responsive frontend page with project cards. Start September 10. Due September 15."

Pass:

"description": "Build a responsive frontend page with project cards."

Never overwrite a user-provided description.

=========================================================
DATE RULES
=========================================================

Project:
- startDate is required.
- deadline is required.

Task:
- startDate is required.
- dueDate is required.

Never invent a date.

Understand natural date expressions such as:
"September 10"
"10 September"
"Sep 10"
"10/09/2026"
"2026-09-10"
"next Monday"
"tomorrow"

Convert dates to YYYY-MM-DD only when the intended date can be determined safely.

If a date is ambiguous, ask the user for clarification.

For project creation:
- deadline should not be earlier than startDate.

For task creation:
- dueDate should not be earlier than startDate.

=========================================================
PRIORITY RULES
=========================================================

Valid priorities:

Low
Medium
High

If user says:
"high priority"
"use high priority"
"make it high priority"

Use:

"priority": "High"

If user does not specify priority:
Use:

"priority": "Medium"

Never create other priority values.

=========================================================
PERMISSION RULES
=========================================================

Always respect the user's role.

Project creation is allowed only for:
- Executive Manager
- System Administrator

Task creation is allowed only for:
- Project Manager
- Executive Manager
- System Administrator

Work submission is allowed only for:
- Member

The backend performs the final permission check.

Never claim that an action was successful until the backend function returns success.

=========================================================
IMPORTANT EXECUTION RULE
=========================================================

Before calling a function, check whether all required information is available.

CREATE PROJECT:

Required:
- name
- domain
- startDate
- deadline

Description:
- optional
- generate automatically by backend if missing

Priority:
- optional
- default Medium

CREATE TASK:

Required:
- name
- projectName OR projectId
- startDate
- dueDate

Description:
- optional
- generate automatically by backend if missing

Priority:
- optional
- default Medium

If required information is missing:
- Do not call the function.
- Ask for the missing information.
- If several required fields are missing, ask for all of them in one concise message.
- Keep all information already supplied by the user.

=========================================================
FINAL RESPONSE STYLE
=========================================================

When asking the user for missing information:
- Be concise.
- Clearly list what is missing.
- Do not ask unnecessary questions.
- Do not ask for optional descriptions.
- Do not ask for priority if it was not provided because it defaults to Medium.

When executing a function:
Return EXACTLY the function call format.

When no function needs to be called:
Respond naturally and professionally.

Be concise and professional.
`;
        // Start chat with history
        const chat = model.startChat({
            history: [
                { role: 'user', parts: [{ text: systemInstruction }] },
                { role: 'model', parts: [{ text: 'I understand. I will help with project management tasks.' }] },
                ...conversationHistory.slice(-5).map(msg => ({
                    role: msg.role === 'assistant' ? 'model' : 'user',
                    parts: [{ text: msg.content }]
                }))
            ]
        });

        // Send message
        console.log('📤 Sending to Gemini...');
        const result = await chat.sendMessage(message);
        const aiResponse = result.response.text();
        console.log('📥 Gemini response received');

        // Parse for function calls
        const parsed = parseAIResponse(aiResponse);

        if (parsed.function_call) {
            const functionName = parsed.function_call.name;
            const params = parsed.function_call.arguments;
            console.log(`⚡ Executing function: ${functionName}`, params);

            if (functions[functionName]) {
                try {
                    const executionResult = await functions[functionName](params, user);
                    console.log(`✅ Function ${functionName} executed`, executionResult);
                    
                    // const finalResponse = await generateFinalResponse(functionName, executionResult, user);

                    // return res.status(200).json({
                    //     success: true,
                    //     message: finalResponse,
                    //     data: executionResult,
                    //     function_called: functionName
                    // });

                    /*
 * If backend needs the user to select a project,

 * don't treat this as a successful task creation.

 */
                    if (executionResult?.requiresProjectSelection) {
                    
                        // Multiple projects with same name
                    
                        if (executionResult.multipleProjects) {
                    
                            const projectList = executionResult.projects
                    
                                .map((project, index) =>
                    
                                    `${index + 1}. ${project.name} — ID: ${project.id}`
                    
                                )
                    
                                .join('\n');
                    
                            return res.status(200).json({
                    
                                success: false,
                    
                                requiresProjectSelection: true,
                    
                                message:
                    
                                    `I found multiple projects named "${executionResult.projectName}". ` +
                    
                                    `Please provide the project ID you want to use.\n\n${projectList}`,
                    
                                data: executionResult,
                    
                                function_called: functionName
                    
                            });
                    
                        }
                    
                        // No project found
                    
                        return res.status(200).json({
                    
                            success: false,
                    
                            requiresProjectSelection: true,
                    
                            message: executionResult.error,
                    
                            data: executionResult,
                    
                            function_called: functionName
                    
                        });
                    
                    }
                    
                    /*
                    
                     * Normal successful execution
                    
                     */
                    
                    const finalResponse = await generateFinalResponse(
                    
                        functionName,
                    
                        executionResult,
                    
                        user
                    
                    );
                    
                    return res.status(200).json({
                    
                        success: true,
                    
                        message: finalResponse,
                    
                        data: executionResult,
                    
                        function_called: functionName
                    
                    });
                    
                } catch (error) {
                    console.error(`❌ Function execution failed: ${functionName}`, error);
                    return res.status(500).json({
                        success: false,
                        error: `Function execution failed: ${error.message}`
                    });
                }
            } else {
                console.error(`❌ Function "${functionName}" not found`);
                return res.status(400).json({
                    success: false,
                    error: `Function "${functionName}" not found`,
                    available_functions: Object.keys(functions)
                });
            }
        }

        // No function call - return AI response directly
        console.log('ℹ️ No function call detected, returning AI response');
        return res.status(200).json({
            success: true,
            message: aiResponse,
            data: null,
            function_called: null
        });

    } catch (error) {
        console.error('❌ AI Agent error:', error);
        return res.status(500).json({
            success: false,
            error: error.message || 'Failed to process AI request',
            ...(process.env.NODE_ENV !== 'production' && { stack: error.stack })
        });
    }
};
