// controllers/aiAgentController.js
const { getChatModel, getModel } = require('../config/gemini');
const projectController = require('./projectcontroller');
const taskController = require('./taskcontroller');
const userController = require('./usercontroller');
const submissionController = require('./tasksubmissioncontroller');

// Helper to get current user
const getCurrentUser = (req) => {
    return req.user || null;
};

// Generate project description
const generateProjectDescription = async (projectName, domain) => {

    try {

        const model = getModel();

        const prompt = `

You are generating a professional project description for a project management system.

Project Name:

"${projectName}"

Project Domain:

"${domain || 'Not specified'}"

Generate a clear and professional project description.

Requirements:

- Write 2-3 sentences.

- Explain what the project is intended to achieve.

- Mention the main purpose or objectives.

- Mention the expected outcome or value.

- Use the project name and domain to make the description specific.

- Do not invent highly specific features that were not implied by the project name or domain.

- Do not mention that the description was generated by AI.

- Do not use Markdown.

- Do not use headings, bullet points, or quotation marks.

- Return ONLY the project description.

Example style:

"This project focuses on developing an intelligent AI-powered platform designed to streamline project management and improve team productivity. It aims to provide efficient tools for managing projects, tasks, and collaboration while delivering better visibility into project progress and outcomes."

`;

        const result = await model.generateContent(prompt);

        const generatedDescription = result.response.text().trim();

        if (!generatedDescription) {

            throw new Error('AI returned an empty project description');

        }

        return generatedDescription;

    } catch (error) {

        console.error('❌ Error generating project description:', error);

        // Safe fallback if Gemini fails

        return domain

            ? `The ${projectName} project focuses on delivering solutions within the ${domain} domain. It aims to achieve its key objectives efficiently while providing meaningful value and measurable outcomes.`

            : `The ${projectName} project focuses on delivering a practical solution to achieve its intended objectives. It aims to provide meaningful value while supporting efficient project execution and successful outcomes.`;

    }

};

exports.generateProjectDescription = generateProjectDescription;

const generateTaskDescription = async (taskName) => {
    try {
        const model = getModel();

        const prompt = `
You are generating a professional task description for a project management system.

Task Name:
"${taskName}"

Generate a useful task description based only on the task name.

Requirements:
- Write 1-2 clear sentences.
- Explain what needs to be completed.
- Make the description practical and actionable.
- Keep it relevant to the task name.
- Do not invent unnecessary project-specific information.
- Do not mention that the description was generated by AI.
- Do not use Markdown.
- Do not use headings or bullet points.
- Return ONLY the task description.

Example:

Task Name:
"Design Frontend Page"

Description:
"Design and implement the required frontend page with a clear, responsive, and user-friendly interface that meets the project's UI requirements."
`;

        const result = await model.generateContent(prompt);

        const generatedDescription = result.response.text().trim();

        if (!generatedDescription) {
            throw new Error('AI returned an empty task description');
        }

        return generatedDescription;

    } catch (error) {
        console.error('❌ Error generating task description:', error);

        return `Complete the "${taskName}" task according to the project requirements and ensure that the expected work is properly implemented.`;
    }
};

exports.generateTaskDescription = generateTaskDescription;

// Helper to safely execute controller functions
const safeExecute = async (controllerFn, req, res) => {
    try {
        const result = await controllerFn(req, res);
        return result;
    } catch (error) {
        console.error('Controller execution error:', error);
        return {
            success: false,
            error: error.message || 'Operation failed'
        };
    }
};

// Function definitions with better error handling
const functions = {
    createProject: async (params, user) => {
        const { name, domain, aboutTitle, aboutDescription, startDate, deadline, priority } = params;

        console.log('🔍 createProject called with:', { name, domain, priority, userRole: user?.role });

        // Check permissions
        if (!['Executive Manager', 'System Administrator'].includes(user?.role)) {
            console.log('❌ Permission denied. User role:', user?.role);
            return {
                success: false,
                error: `Only Executive Managers and System Administrators can create projects. Your role: ${user?.role || 'Unknown'}`
            };
        }

        if (!name) {
            console.log('❌ Project name is missing');
            return { success: false, error: 'Project name is required.' };
        }

        if (!domain || !String(domain).trim()) {
            return {
                success: false,
                error: 'Project domain is required.'
            };
        }

        if (!startDate) {
            return {
                success: false,
                error: 'Project start date is required.'
            };
        }

        if (!deadline) {
            return {
                success: false,
                error: 'Project deadline is required.'
            };
        }

        const start = new Date(startDate);
        const end = new Date(deadline);

        if (
            Number.isNaN(start.getTime()) ||
            Number.isNaN(end.getTime())
        ) {
            return {
                success: false,
                error: 'Invalid project date format. Use YYYY-MM-DD.'
            };
        }

        if (end < start) {
            return {
                success: false,
                error: 'Project deadline cannot be earlier than the start date.'
            };
        }

        // Generate description if not provided
        let description = aboutDescription;
        if (!description && name) {
            console.log('📝 Generating description for:', name);
            try {
                description = await generateProjectDescription(name, domain);
                console.log('✅ Description generated successfully');
            } catch (error) {
                console.error('❌ Failed to generate description:', error);
                description = `A project focused on ${name} to deliver value.`;
            }
        }

        // Prepare request
        const req = {
            body: {
                name,
                domain: domain || null,
                aboutTitle: aboutTitle || name,
                aboutDescription: description,
                startDate: startDate || null,
                deadline: deadline || null,
                priority: priority || 'Medium'
            },
            user: user
        };

        console.log('📤 Sending to projectController.createProject');

        const res = {
            status: (code) => ({
                json: (data) => {
                    console.log(`📥 Response status ${code}:`, data);
                    return { status: code, data };
                },
                send: (data) => {
                    console.log('📥 Response send:', data);
                    return { data };
                }
            })
        };

        try {
            const result = await projectController.createProject(req, res);
            console.log('✅ Project creation result:', result);

            // Check if result has data property
            if (result && result.data) {
                return result.data;
            }
            return result || { success: true, message: 'Project created successfully' };
        } catch (error) {
            console.error('❌ Project creation error:', error);
            return {
                success: false,
                error: error.message || 'Failed to create project',
                details: error.stack
            };
        }
    },

    getProjects: async (params, user) => {
        const {
            status,
            priority,
            managerName,
            managerId,
            deadlineCondition,
            sortBy,
            sortOrder
        } = params || {};

        console.log("🔍 getProjects called:", {
            status,
            priority,
            managerName,
            managerId,
            deadlineCondition,
            sortBy,
            sortOrder,
            user: user?.id,
            role: user?.role
        });

        const req = {
            user
        };

        const res = {
            status: (code) => ({
                json: (data) => ({
                    status: code,
                    data
                }),
                send: (data) => ({
                    data
                })
            })
        };

        try {
            const result = await projectController.getProjects(req, res);

            const responseData = result?.data || result;

            let projects = Array.isArray(responseData)
                ? responseData
                : responseData?.projects || [];

            console.log(`📦 ${projects.length} projects received from backend`);

            // =====================================================
            // FILTER BY STATUS
            // =====================================================

            if (status) {
                const normalizedStatus = String(status)
                    .trim()
                    .toLowerCase();

                projects = projects.filter(project =>
                    String(project.status || "")
                        .trim()
                        .toLowerCase() === normalizedStatus
                );
            }

            // =====================================================
            // FILTER BY PRIORITY
            // =====================================================

            if (priority) {
                const normalizedPriority = String(priority)
                    .trim()
                    .toLowerCase();

                projects = projects.filter(project =>
                    String(project.priority || "")
                        .trim()
                        .toLowerCase() === normalizedPriority
                );
            }

            // =====================================================
            // FILTER BY MANAGER ID
            // =====================================================

            if (managerId) {
                projects = projects.filter(project =>
                    String(
                        project.managerId ||
                        project.projectManagerId ||
                        project.assignedManagerId ||
                        ""
                    ) === String(managerId)
                );
            }

            // =====================================================
            // FILTER BY MANAGER NAME
            // =====================================================

            if (managerName) {
                const normalizedManagerName = String(managerName)
                    .trim()
                    .toLowerCase();

                projects = projects.filter(project => {
                    const currentManagerName = String(
                        project.managerName ||
                        project.managerFullName ||
                        project.manager?.fullName ||
                        ""
                    )
                        .trim()
                        .toLowerCase();

                    return currentManagerName === normalizedManagerName;
                });
            }

            // =====================================================
            // DEADLINE FILTERS
            // =====================================================

            const today = new Date();
            today.setHours(0, 0, 0, 0);

            if (deadlineCondition) {

                if (deadlineCondition === "overdue") {

                    projects = projects.filter(project => {
                        if (!project.deadline) return false;

                        const deadline = new Date(project.deadline);
                        deadline.setHours(0, 0, 0, 0);

                        return deadline < today &&
                            String(project.status || "").toLowerCase() !== "done";
                    });
                }

                else if (deadlineCondition === "upcoming") {

                    projects = projects.filter(project => {
                        if (!project.deadline) return false;

                        const deadline = new Date(project.deadline);
                        deadline.setHours(0, 0, 0, 0);

                        return deadline >= today;
                    });
                }

                else if (deadlineCondition === "extended") {

                    /*
                     * This assumes your project response contains
                     * either deadlineExtended / deadlineChanged /
                     * originalDeadline metadata.
                     *
                     * If your DB uses a different field, adjust here.
                     */

                    projects = projects.filter(project =>
                        project.deadlineExtended === true ||
                        project.deadlineChanged === true ||
                        Boolean(project.originalDeadline)
                    );
                }
            }

            // =====================================================
            // SORT
            // =====================================================

            const field = sortBy || "name";
            const direction =
                String(sortOrder || "asc").toLowerCase() === "desc"
                    ? -1
                    : 1;

            projects.sort((a, b) => {

                let valueA = a[field];
                let valueB = b[field];

                if (field === "deadline" || field === "startDate") {

                    valueA = valueA
                        ? new Date(valueA).getTime()
                        : 0;

                    valueB = valueB
                        ? new Date(valueB).getTime()
                        : 0;

                } else {

                    valueA = String(valueA || "")
                        .toLowerCase();

                    valueB = String(valueB || "")
                        .toLowerCase();
                }

                if (valueA < valueB) return -1 * direction;
                if (valueA > valueB) return 1 * direction;

                return 0;
            });

            return {
                success: true,
                projects
            };

        } catch (error) {

            console.error("❌ Get projects error:", error);

            return {
                success: false,
                error: error.message || "Failed to get projects",
                projects: []
            };
        }
    },

    getTasks: async (params, user) => {

        const {
            taskName,
            taskId,
            projectName,
            projectId,
            status,
            assigneeName,
            assigneeId
        } = params || {};

        console.log("🔍 getTasks called:", {
            taskName,
            taskId,
            projectName,
            projectId,
            status,
            assigneeName,
            assigneeId,
            user: user?.id,
            role: user?.role
        });

        const req = {
            user,
            query: {
                taskName,
                taskId,
                projectName,
                projectId,
                status,
                assigneeName,
                assigneeId
            }
        };

        const res = {
            status: (code) => ({
                json: (data) => ({
                    status: code,
                    data
                }),
                send: (data) => ({
                    data
                })
            })
        };

        try {

            /*
             * IMPORTANT:
             *
             * This assumes your taskController has a getTasks
             * function that returns tasks visible to the current user.
             *
             * If your existing controller uses another method,
             * connect that method here.
             */

            const result = await taskController.getTasks(req, res);

            const responseData = result?.data || result;

            let tasks = Array.isArray(responseData)
                ? responseData
                : responseData?.tasks || [];

            // =====================================================
            // TASK NAME
            // =====================================================

            if (taskName) {

                const normalizedName = String(taskName)
                    .trim()
                    .toLowerCase();

                tasks = tasks.filter(task =>
                    String(task.name || task.taskName || "")
                        .trim()
                        .toLowerCase() === normalizedName
                );
            }

            // =====================================================
            // TASK ID
            // =====================================================

            if (taskId) {

                tasks = tasks.filter(task =>
                    String(task.id) === String(taskId)
                );
            }

            // =====================================================
            // PROJECT ID
            // =====================================================

            if (projectId) {

                tasks = tasks.filter(task =>
                    String(
                        task.projectId ||
                        task.project_id ||
                        ""
                    ) === String(projectId)
                );
            }

            // =====================================================
            // PROJECT NAME
            // =====================================================

            if (projectName) {

                const normalizedProjectName =
                    String(projectName)
                        .trim()
                        .toLowerCase();

                tasks = tasks.filter(task =>
                    String(
                        task.projectName ||
                        task.project?.name ||
                        ""
                    )
                        .trim()
                        .toLowerCase() === normalizedProjectName
                );
            }

            // =====================================================
            // STATUS
            // =====================================================

            if (status) {

                const normalizedStatus =
                    String(status)
                        .trim()
                        .toLowerCase();

                tasks = tasks.filter(task =>
                    String(task.status || "")
                        .trim()
                        .toLowerCase() === normalizedStatus
                );
            }

            // =====================================================
            // ASSIGNEE ID
            // =====================================================

            if (assigneeId) {

                tasks = tasks.filter(task =>
                    String(
                        task.assigneeId ||
                        task.assignee_id ||
                        ""
                    ) === String(assigneeId)
                );
            }

            // =====================================================
            // ASSIGNEE NAME
            // =====================================================

            if (assigneeName) {

                const normalizedAssigneeName =
                    String(assigneeName)
                        .trim()
                        .toLowerCase();

                tasks = tasks.filter(task =>
                    String(
                        task.assigneeName ||
                        task.assigneeFullName ||
                        task.assignee?.fullName ||
                        ""
                    )
                        .trim()
                        .toLowerCase() === normalizedAssigneeName
                );
            }

            return {
                success: true,
                tasks
            };

        } catch (error) {

            console.error("❌ Get tasks error:", error);

            return {
                success: false,
                error: error.message || "Failed to get tasks",
                tasks: []
            };
        }
    },

    createTask: async (params, user) => {

        const {
            projectId,
            projectName,
            name,
            description,
            status,
            priority,
            assigneeId,
            startDate,
            dueDate
        } = params;

        console.log('🔍 createTask called:', {
            projectId,
            projectName,
            name,
            startDate,
            dueDate,
            userRole: user?.role
        });

        // =====================================================
        // PERMISSION CHECK
        // =====================================================

        if (
            ![
                'Executive Manager',
                'System Administrator',
                'Project Manager'
            ].includes(user?.role)
        ) {
            return {
                success: false,
                error: 'Only Project Managers and above can create tasks.'
            };
        }

        // =====================================================
        // REQUIRED TASK NAME
        // =====================================================

        if (!name || !String(name).trim()) {
            return {
                success: false,
                error: 'Task name is required.'
            };
        }

        // =====================================================
        // REQUIRED DATES
        // =====================================================

        if (!startDate) {
            return {
                success: false,
                error: 'Task start date is required.'
            };
        }

        if (!dueDate) {
            return {
                success: false,
                error: 'Task due date is required.'
            };
        }

        // =====================================================
        // DATE VALIDATION
        // =====================================================

        if (startDate && dueDate) {

            const start = new Date(startDate);
            const due = new Date(dueDate);

            if (
                Number.isNaN(start.getTime()) ||
                Number.isNaN(due.getTime())
            ) {
                return {
                    success: false,
                    error: 'Invalid task date format. Use YYYY-MM-DD.'
                };
            }

            if (due < start) {
                return {
                    success: false,
                    error: 'Task due date cannot be earlier than the start date.'
                };
            }
        }

        // =====================================================
        // RESOLVE PROJECT
        // =====================================================

        let resolvedProjectId = projectId || null;
        let resolvedProjectName = projectName || null;

        /*
         * If project ID is provided, trust it.
         *
         * If project name is provided instead, search for the
         * exact project name.
         */

        if (!resolvedProjectId && projectName) {

            console.log(
                `🔎 Searching project by name: "${projectName}"`
            );

            const projectsReq = {
                user
            };

            const projectsRes = {
                status: (code) => ({
                    json: (data) => ({
                        status: code,
                        data
                    }),

                    send: (data) => ({
                        data
                    })
                })
            };

            try {

                const projectsResult =
                    await projectController.getProjects(
                        projectsReq,
                        projectsRes
                    );

                const projectsData =
                    projectsResult?.data || projectsResult;

                console.log(
                    '📦 Projects returned:',
                    projectsData
                );

                const projects =
                    Array.isArray(projectsData)
                        ? projectsData
                        : projectsData?.projects || [];

                // Normalize project name
                const normalizedProjectName =
                    String(projectName)
                        .trim()
                        .toLowerCase();

                // Exact case-insensitive match
                const matchedProjects =
                    projects.filter((project) => {

                        const currentName =
                            String(
                                project.name ||
                                project.projectName ||
                                ''
                            )
                                .trim()
                                .toLowerCase();

                        return currentName === normalizedProjectName;
                    });

                console.log(
                    `🔎 Found ${matchedProjects.length} project(s) matching "${projectName}"`
                );

                // =================================================
                // NO PROJECT FOUND
                // =================================================

                if (matchedProjects.length === 0) {

                    return {
                        success: false,

                        requiresProjectSelection: true,

                        projectName,

                        error:
                            `No project named "${projectName}" was found. ` +
                            `Please provide the exact project name.`
                    };
                }

                // =================================================
                // MULTIPLE PROJECTS FOUND
                // =================================================

                if (matchedProjects.length > 1) {

                    const projectOptions =
                        matchedProjects.map((project) => ({
                            id: project.id,
                            name:
                                project.name ||
                                project.projectName,
                            status:
                                project.status || null
                        }));

                    return {

                        success: false,

                        requiresProjectSelection: true,

                        multipleProjects: true,

                        projectName,

                        projects: projectOptions,

                        error:
                            `Multiple projects named "${projectName}" were found. ` +
                            `Please provide the project ID.`
                    };
                }

                // =================================================
                // EXACTLY ONE PROJECT FOUND
                // =================================================

                resolvedProjectId =
                    matchedProjects[0].id;

                resolvedProjectName =
                    matchedProjects[0].name ||
                    matchedProjects[0].projectName ||
                    projectName;

                console.log(
                    `✅ Project resolved: "${resolvedProjectName}" → ID ${resolvedProjectId}`
                );

            } catch (error) {

                console.error(
                    '❌ Project name resolution error:',
                    error
                );

                return {

                    success: false,

                    error:
                        'Unable to find the project. Please try again or provide the project ID.'
                };
            }
        }

        // =====================================================
        // PROJECT REQUIRED
        // =====================================================

        if (!resolvedProjectId) {

            return {
                success: false,

                requiresProjectSelection: true,

                error:
                    'Please provide a project name or project ID.'
            };
        }

        // =====================================================
        // GENERATE TASK DESCRIPTION IF MISSING
        // =====================================================

        let finalDescription = description;

        if (
            !finalDescription ||
            !String(finalDescription).trim()
        ) {

            console.log(
                `📝 No task description provided. Generating description for: "${name}"`
            );

            finalDescription =
                await generateTaskDescription(name);

            console.log(
                '✅ Task description generated successfully'
            );
        }

        // =====================================================
        // PREPARE REQUEST FOR TASK CONTROLLER
        // =====================================================

        const req = {

            params: {
                projectId: resolvedProjectId
            },

            body: {

                name: String(name).trim(),

                /*
                 * IMPORTANT:
                 * Use finalDescription here.
                 *
                 * If user supplied a description:
                 *     → their exact description is preserved.
                 *
                 * If user did not supply one:
                 *     → generated description is used.
                 */
                description: finalDescription,

                status: status || 'To Do',

                priority: priority || 'Medium',

                assigneeId: assigneeId || null,

                startDate,

                dueDate
            },

            user
        };

        console.log(
            '📤 Sending task to taskController.createTask:',
            {
                projectId: resolvedProjectId,
                projectName: resolvedProjectName,
                name,
                startDate,
                dueDate,
                priority: priority || 'Medium',
                descriptionGenerated: !description
            }
        );

        // =====================================================
        // MOCK RESPONSE OBJECT
        // =====================================================

        const res = {

            status: (code) => ({

                json: (data) => ({
                    status: code,
                    data
                }),

                send: (data) => ({
                    data
                })
            })
        };

        // =====================================================
        // CREATE TASK
        // =====================================================

        try {

            const result =
                await taskController.createTask(
                    req,
                    res
                );

            const taskResult =
                result?.data || result;

            console.log(
                '✅ Task creation result:',
                taskResult
            );

            return {

                ...taskResult,

                projectId: resolvedProjectId,

                projectName: resolvedProjectName
            };

        } catch (error) {

            console.error(
                '❌ Create task error:',
                error
            );

            return {

                success: false,

                error:
                    error.message ||
                    'Failed to create task'
            };
        }
    },

    assignProject: async (params, user) => {

        const {
            projectId,
            projectName,
            managerId,
            managerName
        } = params || {};

        console.log("🔍 assignProject called:", {
            projectId,
            projectName,
            managerId,
            managerName,
            userRole: user?.role
        });

        // =====================================================
        // PERMISSION
        // =====================================================

        if (
            ![
                "Executive Manager",
                "System Administrator"
            ].includes(user?.role)
        ) {
            return {
                success: false,
                error:
                    "Only Executive Managers and System Administrators can assign projects."
            };
        }

        // =====================================================
        // PROJECT REQUIRED
        // =====================================================

        if (!projectId && !projectName) {

            return {
                success: false,
                requiresProjectSelection: true,
                error: "Please provide the project name or project ID."
            };
        }

        // =====================================================
        // MANAGER REQUIRED
        // =====================================================

        if (!managerId && !managerName) {

            return {
                success: false,
                requiresManagerSelection: true,
                error:
                    "Please provide the Project Manager name or manager ID."
            };
        }

        // =====================================================
        // RESOLVE PROJECT
        // =====================================================

        let resolvedProjectId = projectId;
        let resolvedProjectName = projectName;

        if (!resolvedProjectId) {

            const projectResult =
                await functions.getProjects({}, user);

            if (!projectResult.success) {
                return projectResult;
            }

            const projects =
                projectResult.projects || [];

            const normalizedName =
                String(projectName)
                    .trim()
                    .toLowerCase();

            const matches =
                projects.filter(project =>
                    String(
                        project.name ||
                        project.projectName ||
                        ""
                    )
                        .trim()
                        .toLowerCase() === normalizedName
                );

            if (matches.length === 0) {

                return {
                    success: false,
                    requiresProjectSelection: true,
                    projectName,
                    error:
                        `No project named "${projectName}" was found.`
                };
            }

            if (matches.length > 1) {

                return {
                    success: false,
                    requiresProjectSelection: true,
                    multipleProjects: true,
                    projectName,

                    projects: matches.map(project => ({
                        id: project.id,
                        name:
                            project.name ||
                            project.projectName,
                        status: project.status || null,
                        priority: project.priority || null
                    })),

                    error:
                        `Multiple projects named "${projectName}" were found.`
                };
            }

            resolvedProjectId = matches[0].id;

            resolvedProjectName =
                matches[0].name ||
                matches[0].projectName ||
                projectName;
        }

        // =====================================================
        // RESOLVE MANAGER
        // =====================================================

        let resolvedManagerId = managerId;
        let resolvedManagerName = managerName;

        if (!resolvedManagerId) {

            const managerResult =
                await functions.getProjectManagers({}, user);

            if (!managerResult.success) {
                return managerResult;
            }

            const managers =
                managerResult.projectManagers ||
                managerResult.managers ||
                managerResult.users ||
                [];

            const normalizedName =
                String(managerName)
                    .trim()
                    .toLowerCase();

            const matches =
                managers.filter(manager =>
                    String(
                        manager.fullName ||
                        manager.name ||
                        manager.userName ||
                        ""
                    )
                        .trim()
                        .toLowerCase() === normalizedName
                );

            if (matches.length === 0) {

                return {
                    success: false,
                    requiresManagerSelection: true,
                    managerName,

                    error:
                        `No Project Manager named "${managerName}" was found.`
                };
            }

            if (matches.length > 1) {

                return {
                    success: false,
                    requiresManagerSelection: true,
                    multipleManagers: true,
                    managerName,

                    managers: matches.map(manager => ({
                        id: manager.id,
                        fullName:
                            manager.fullName ||
                            manager.name ||
                            manager.userName,
                        email: manager.email || null
                    })),

                    error:
                        `Multiple Project Managers named "${managerName}" were found.`
                };
            }

            resolvedManagerId = matches[0].id;

            resolvedManagerName =
                matches[0].fullName ||
                matches[0].name ||
                matches[0].userName ||
                managerName;
        }

        // =====================================================
        // ASSIGN PROJECT
        // =====================================================

        const req = {

            params: {
                projectId: resolvedProjectId
            },

            body: {
                managerId: resolvedManagerId
            },

            user
        };

        const res = {

            status: (code) => ({

                json: (data) => ({
                    status: code,
                    data
                }),

                send: (data) => ({
                    data
                })
            })
        };

        try {

            const result =
                await projectController.assignProject(
                    req,
                    res
                );

            const assignmentResult =
                result?.data || result;

            return {

                ...assignmentResult,

                projectId: resolvedProjectId,

                projectName: resolvedProjectName,

                managerId: resolvedManagerId,

                managerName: resolvedManagerName
            };

        } catch (error) {

            console.error(
                "❌ Assign project error:",
                error
            );

            return {
                success: false,
                error:
                    error.message ||
                    "Failed to assign project"
            };
        }
    },

    assignTask: async (params, user) => {

        const {
            taskId,
            taskName,
            assigneeId,
            assigneeName
        } = params || {};

        console.log("🔍 assignTask called:", {
            taskId,
            taskName,
            assigneeId,
            assigneeName,
            userRole: user?.role
        });

        // =====================================================
        // PERMISSION
        // =====================================================

        if (
            ![
                "Executive Manager",
                "System Administrator",
                "Project Manager"
            ].includes(user?.role)
        ) {
            return {
                success: false,
                error:
                    "Only Project Managers and above can assign tasks."
            };
        }

        // =====================================================
        // TASK REQUIRED
        // =====================================================

        if (!taskId && !taskName) {

            return {
                success: false,
                requiresTaskSelection: true,
                error:
                    "Please provide the task name or task ID."
            };
        }

        // =====================================================
        // MEMBER REQUIRED
        // =====================================================

        if (!assigneeId && !assigneeName) {

            return {
                success: false,
                requiresAssigneeSelection: true,
                error:
                    "Please provide the Member name or Member ID."
            };
        }

        // =====================================================
        // RESOLVE TASK
        // =====================================================

        let resolvedTaskId = taskId;
        let resolvedTaskName = taskName;

        if (!resolvedTaskId) {

            const taskResult =
                await functions.getTasks(
                    {
                        taskName
                    },
                    user
                );

            if (!taskResult.success) {
                return taskResult;
            }

            const tasks =
                taskResult.tasks || [];

            if (tasks.length === 0) {

                return {
                    success: false,
                    requiresTaskSelection: true,
                    taskName,
                    error:
                        `No task named "${taskName}" was found.`
                };
            }

            if (tasks.length > 1) {

                return {
                    success: false,
                    requiresTaskSelection: true,
                    multipleTasks: true,
                    taskName,

                    tasks: tasks.map(task => ({
                        id: task.id,
                        name:
                            task.name ||
                            task.taskName,
                        projectId:
                            task.projectId ||
                            task.project_id ||
                            null,
                        projectName:
                            task.projectName ||
                            task.project?.name ||
                            null,
                        status: task.status || null
                    })),

                    error:
                        `Multiple tasks named "${taskName}" were found.`
                };
            }

            resolvedTaskId = tasks[0].id;

            resolvedTaskName =
                tasks[0].name ||
                tasks[0].taskName ||
                taskName;
        }

        // =====================================================
        // RESOLVE MEMBER
        // =====================================================

        let resolvedAssigneeId = assigneeId;
        let resolvedAssigneeName = assigneeName;

        if (!resolvedAssigneeId) {

            const usersResult =
                await functions.getUsers({}, user);

            if (!usersResult.success) {
                return usersResult;
            }

            const users =
                usersResult.users || [];

            const members =
                users.filter(
                    currentUser =>
                        currentUser.role === "Member"
                );

            const normalizedName =
                String(assigneeName)
                    .trim()
                    .toLowerCase();

            const matches =
                members.filter(member =>
                    String(
                        member.fullName ||
                        member.name ||
                        ""
                    )
                        .trim()
                        .toLowerCase() === normalizedName
                );

            if (matches.length === 0) {

                return {
                    success: false,
                    requiresAssigneeSelection: true,
                    assigneeName,

                    error:
                        `No Member named "${assigneeName}" was found.`
                };
            }

            if (matches.length > 1) {

                return {
                    success: false,
                    requiresAssigneeSelection: true,
                    multipleAssignees: true,
                    assigneeName,

                    members: matches.map(member => ({
                        id: member.id,
                        fullName:
                            member.fullName ||
                            member.name,
                        email: member.email || null,
                        role: member.role
                    })),

                    error:
                        `Multiple Members named "${assigneeName}" were found.`
                };
            }

            resolvedAssigneeId = matches[0].id;

            resolvedAssigneeName =
                matches[0].fullName ||
                matches[0].name ||
                assigneeName;
        }

        // =====================================================
        // CALL TASK CONTROLLER
        // =====================================================

        const req = {

            params: {
                taskId: resolvedTaskId
            },

            body: {
                assigneeId: resolvedAssigneeId
            },

            user
        };

        const res = {

            status: (code) => ({

                json: (data) => ({
                    status: code,
                    data
                }),

                send: (data) => ({
                    data
                })
            })
        };

        try {

            /*
             * IMPORTANT:
             *
             * Your existing assignment controller should use
             * the current endpoint/controller method.
             *
             * If your controller currently calls this:
             *
             * taskController.assignTask
             *
             * use it here.
             *
             * If the method is currently named assignAssignee,
             * change the next line accordingly.
             */

            const result =
                await taskController.assignTask(
                    req,
                    res
                );

            const assignmentResult =
                result?.data || result;

            return {

                ...assignmentResult,

                taskId: resolvedTaskId,

                taskName: resolvedTaskName,

                assigneeId: resolvedAssigneeId,

                assigneeName: resolvedAssigneeName
            };

        } catch (error) {

            console.error(
                "❌ Assign task error:",
                error
            );

            return {
                success: false,
                error:
                    error.message ||
                    "Failed to assign task"
            };
        }
    },

    updateTaskStatus: async (params, user) => {
        const { taskId, status } = params;

        if (!['Executive Manager', 'System Administrator', 'Project Manager'].includes(user?.role)) {
            return { success: false, error: 'Only Project Managers and above can update task status.' };
        }

        if (!taskId || !status) {
            return { success: false, error: 'Task ID and status are required.' };
        }

        const req = {
            params: { taskId },
            body: { status },
            user: user
        };

        const res = {
            status: (code) => ({
                json: (data) => ({ status: code, data }),
                send: (data) => ({ data })
            })
        };

        try {
            const result = await taskController.updateTaskStatus(req, res);
            return result.data || result;
        } catch (error) {
            console.error('❌ Update task status error:', error);
            return { success: false, error: error.message || 'Failed to update task status' };
        }
    },

    deleteTask: async (params, user) => {
        const { taskId } = params;

        if (!['Executive Manager', 'System Administrator', 'Project Manager'].includes(user?.role)) {
            return { success: false, error: 'Only Project Managers and above can delete tasks.' };
        }

        if (!taskId) {
            return { success: false, error: 'Task ID is required.' };
        }

        const req = {
            params: { taskId },
            user: user
        };

        const res = {
            status: (code) => ({
                json: (data) => ({ status: code, data }),
                send: (data) => ({ data })
            })
        };

        try {
            const result = await taskController.deleteTask(req, res);
            return result.data || result;
        } catch (error) {
            console.error('❌ Delete task error:', error);
            return { success: false, error: error.message || 'Failed to delete task' };
        }
    },

    submitWork: async (params, user) => {
        const { taskId, link, description } = params;

        if (user?.role !== 'Member') {
            return { success: false, error: 'Only Members can submit work for tasks.' };
        }

        if (!taskId || !link) {
            return { success: false, error: 'Task ID and link are required.' };
        }

        const req = {
            params: { taskId },
            body: { link, description: description || null },
            user: user
        };

        const res = {
            status: (code) => ({
                json: (data) => ({ status: code, data }),
                send: (data) => ({ data })
            })
        };

        try {
            const result = await submissionController.addSubmission(req, res);
            return result.data || result;
        } catch (error) {
            console.error('❌ Submit work error:', error);
            return { success: false, error: error.message || 'Failed to submit work' };
        }
    },

    getProjectManagers: async (params, user) => {

        const req = {

            user

        };

        const res = {

            status: (code) => ({

                json: (data) => ({

                    status: code,

                    data

                }),

                send: (data) => ({

                    data

                })

            })

        };

        try {

            const result =

                await projectController.getProjectManagers(

                    req,

                    res

                );

            const data =

                result?.data || result;

            const managers =

                data?.projectManagers ||

                data?.managers ||

                data?.users ||

                (Array.isArray(data) ? data : []);

            return {

                success: true,

                projectManagers: managers

            };

        } catch (error) {

            console.error(

                "❌ Get project managers error:",

                error

            );

            return {

                success: false,

                error:

                    error.message ||

                    "Failed to get project managers",

                projectManagers: []

            };

        }

    },

    getUsers: async (params, user) => {

        const req = {
            user
        };

        const res = {

            status: (code) => ({

                json: (data) => ({
                    status: code,
                    data
                }),

                send: (data) => ({
                    data
                })
            })
        };

        try {

            const result =
                await userController.getUsers(
                    req,
                    res
                );

            const data =
                result?.data || result;

            const users =
                data?.users ||
                (Array.isArray(data) ? data : []);

            return {
                success: true,
                users
            };

        } catch (error) {

            console.error(
                "❌ Get users error:",
                error
            );

            return {
                success: false,
                error:
                    error.message ||
                    "Failed to get users",
                users: []
            };
        }
    },
};

// Parse AI response for function calls
const parseAIResponse = (response) => {
    console.log('🔍 Parsing AI response:', response?.substring(0, 200) + '...');

    const functionRegex = /\[FUNCTION:(\w+)\]({[^}]*})/g;
    const match = functionRegex.exec(response);

    if (match) {
        try {
            const functionName = match[1];
            const arguments = JSON.parse(match[2]);
            console.log(`✅ Parsed function: ${functionName}`, arguments);
            return {
                function_call: { name: functionName, arguments: arguments },
                response: response.replace(match[0], '').trim()
            };
        } catch (error) {
            console.error('❌ Failed to parse function call:', error);
            console.error('Raw match:', match[0]);
        }
    }

    console.log('ℹ️ No function call found in response');
    return { function_call: null, response };
};

// Generate final response
const generateFinalResponse = async (functionName, result, user) => {
    try {
        const model = getModel();
        const prompt = `
        A user executed the function "${functionName}".
        Result: ${JSON.stringify(result, null, 2)}
        
        Generate a brief, professional response summarizing what happened.
        If successful, confirm with details.
        If error, explain clearly.
        Keep it to 2-3 sentences.
        `;

        const aiResult = await model.generateContent(prompt);
        return aiResult.response.text().trim();
    } catch (error) {
        console.error('Error generating final response:', error);
        return `Executed ${functionName}. Check the results for details.`;
    }
};

// Main handler
exports.handleAIAgent = async (req, res) => {
    try {
        const { message, conversationHistory = [] } = req.body;
        const user = getCurrentUser(req);

        console.log('=== 🤖 AI Agent Request ===');
        console.log('User:', user?.id, user?.role);
        console.log('Message:', message?.substring(0, 100) + '...');

        if (!message) {
            return res.status(400).json({ success: false, error: 'Message is required' });
        }

        // Check API key
        const apiKey = process.env.GOOGLE_API_KEY || process.env.GOOGLE_AI_API_KEY;
        if (!apiKey) {
            console.error('❌ Google AI API key is not configured');
            return res.status(500).json({
                success: false,
                error: 'Google AI API key is not configured. Please add GOOGLE_API_KEY to your environment variables.'
            });
        }
        console.log('✅ API key configured');

        // Get chat model
        let model;
        try {
            model = getChatModel();
            console.log('✅ Chat model initialized');
        } catch (error) {
            console.error('❌ Model init error:', error);
            return res.status(500).json({
                success: false,
                error: 'Failed to initialize AI model. Please check your API key.'
            });
        }

        // Build the prompt with system instructions
        const systemInstruction = `
You are an AI assistant for a Project Management System.

You help users manage:
- Projects
- Tasks
- Project assignments
- Task assignments
- Task work submissions
- Project and task information

Your job is to understand natural-language requests, collect required information when necessary, resolve real database records through backend functions, and call the appropriate backend function only when enough information is available.

=========================================================
CORE PRINCIPLES
=========================================================

1. PostgreSQL/backend data is the source of truth.

2. NEVER invent:
- IDs
- Project names
- Task names
- User names
- Manager names
- Dates
- Descriptions
- Statuses
- Priorities
- Deadlines
- Work links
- Database information

3. When the user asks for existing projects, tasks, users, or managers:
- Always use the appropriate backend function.
- Never answer from memory.
- Never fabricate records.

4. When the user asks to perform an action:
- Call the appropriate backend function only when all required information is available.

5. Never claim an action succeeded until the backend function returns success.

6. Always respect the user's role and backend permissions.

7. If multiple database records match a name:
- NEVER choose one automatically.
- Ask the user for the required ID.
- Preserve all information already supplied by the user.

8. Names should normally be used by the user.
The backend is responsible for resolving names to actual database IDs.

=========================================================
AVAILABLE FUNCTIONS
=========================================================

1. createProject

Parameters:

{
  "name": "string",
  "domain": "string|null",
  "aboutTitle": "string|null",
  "aboutDescription": "string|null",
  "startDate": "YYYY-MM-DD|null",
  "deadline": "YYYY-MM-DD|null",
  "priority": "Low|Medium|High"
}

Purpose:
Creates a new project.

Required:
- name
- domain
- startDate
- deadline

Optional:
- aboutTitle
- aboutDescription
- priority

Project description behavior:
- If the user provides a description, preserve it exactly.
- Never replace a user-provided description with an AI-generated description.
- If no description is provided, do not ask for one.
- Send aboutDescription as null or omit it.
- The backend will generate the description automatically when needed.

Priority behavior:
- If user specifies Low, use Low.
- If user specifies Medium, use Medium.
- If user specifies High, use High.
- If priority is not specified, use Medium.

Never call createProject when:
- domain is missing
- startDate is missing
- deadline is missing

=========================================================

2. getProjects

Parameters:

{
  "status": "string|null",
  "priority": "Low|Medium|High|null",
  "managerName": "string|null",
  "managerId": "string|null",
  "deadlineCondition": "overdue|upcoming|extended|null",
  "sortBy": "name|startDate|deadline|priority|status|null",
  "sortOrder": "asc|desc|null"
}

Purpose:
Gets real projects available to the current user.

Use this whenever the user asks to:
- see projects
- show projects
- list projects
- give projects
- bring projects
- find projects
- display projects
- know what projects exist

The returned backend records are the ONLY source of truth.

Never invent project names or project information.

=========================================================

3. createTask

Parameters:

{
  "projectName": "string|null",
  "projectId": "string|null",
  "name": "string",
  "description": "string|null",
  "status": "string|null",
  "priority": "Low|Medium|High",
  "assigneeId": "string|null",
  "startDate": "YYYY-MM-DD|null",
  "dueDate": "YYYY-MM-DD|null"
}

Purpose:
Creates a task inside a project.

Required:
- task name
- projectName OR projectId
- startDate
- dueDate

Optional:
- description
- status
- priority
- assigneeId

Task description behavior:
- If the user provides a description, preserve it exactly.
- If no description is provided, do not ask for one.
- Send description as null or omit it.
- The backend generates the description automatically.

Priority:
- Low
- Medium
- High
- Default: Medium

Status:
- If user specifies a status, preserve it.
- If no status is specified, allow backend default.

=========================================================

4. updateTaskStatus

Parameters:

{
  "taskId": "string",
  "status": "string"
}

Purpose:
Updates an existing task status.

Required:
- taskId
- status

Never invent taskId.

If the user provides a task name instead of an ID and a task lookup function is available, resolve the real task first.

=========================================================

5. deleteTask

Parameters:

{
  "taskId": "string"
}

Purpose:
Deletes an existing task.

Required:
- taskId

Never invent taskId.

=========================================================

6. assignProject

Parameters:

{
  "projectName": "string|null",
  "projectId": "string|null",
  "managerName": "string|null",
  "managerId": "string|null"
}

Purpose:
Assigns a project to a Project Manager.

Required:
- projectName OR projectId
- managerName OR managerId

Normal usage:
Users should normally provide names rather than IDs.

Example:

User:
Assign AI Chatbot to Tony Stark

Return:

[FUNCTION:assignProject]{"projectName":"AI Chatbot","managerName":"Tony Stark"}

The backend must resolve:
- projectName -> real project ID
- managerName -> real Project Manager ID

IMPORTANT:
Only Project Managers can receive projects.

If multiple projects have the same name:
- Do not choose one.
- Ask the user for the project ID.

If multiple Project Managers have the same name:
- Do not choose one.
- Ask the user for the manager ID.

Never invent IDs.

=========================================================

7. submitWork

Parameters:

{
  "taskId": "string",
  "link": "string",
  "description": "string|null"
}

Purpose:
Allows a Member to submit work for a task using a link.

Required:
- taskId
- link

Optional:
- description

Only Members can submit work.

Never invent task IDs or work links.

=========================================================

8. getProjectManagers

Parameters:

{}

Purpose:
Gets real Project Managers from the backend.

Use this when:
- resolving a manager by name
- checking whether a person is a Project Manager
- assigning a project to a manager

Never invent managers.

=========================================================

9. getUsers

Parameters:

{}

Purpose:
Gets real users available to the current user.

Use this when:
- resolving a Member by name
- resolving a user by name
- assigning a task
- checking a user's actual role

Never invent users.

=========================================================

10. getTasks

Parameters:

{
  "taskName": "string|null",
  "taskId": "string|null",
  "projectName": "string|null",
  "projectId": "string|null",
  "status": "string|null",
  "assigneeName": "string|null",
  "assigneeId": "string|null"
}

Purpose:
Gets real tasks available to the current user.

Use this when:
- finding tasks
- resolving a task by name
- resolving duplicate task names
- assigning a task
- checking task information

Never invent task IDs or task information.

=========================================================

11. assignTask

Parameters:

{
  "taskName": "string|null",
  "taskId": "string|null",
  "assigneeName": "string|null",
  "assigneeId": "string|null"
}

Purpose:
Assigns a task to a Member.

Required:
- taskName OR taskId
- assigneeName OR assigneeId

Only these roles can assign tasks:
- Project Manager
- Executive Manager
- System Administrator

Only a user with role Member can receive a task.

Normal usage:

User:
Assign Design Login Page to Tony Stark

Return:

[FUNCTION:assignTask]{"taskName":"Design Login Page","assigneeName":"Tony Stark"}

The backend must resolve:
- taskName -> real task ID
- assigneeName -> real Member ID

If multiple tasks have the same name:
- Do not choose one.
- Ask for the task ID.

If multiple Members have the same name:
- Do not choose one.
- Ask for the Member ID.

Never invent IDs.

=========================================================
PROJECT LISTING INTELLIGENCE
=========================================================

When the user asks for projects, ALWAYS use getProjects.

Never answer project-listing requests from memory.

Understand many natural-language variations.

Examples:

"give me projects"
"give projects"
"show projects"
"list projects"
"bring projects"
"bring me projects"
"what projects do we have"
"show me all projects"
"list down the projects"
"what projects are available"
"which projects do we have"
"show all my projects"

These mean:

[FUNCTION:getProjects]{"sortBy":"name","sortOrder":"asc"}

=========================================================
PROJECT STATUS FILTERS
=========================================================

When the user asks for In Progress projects:

Examples:

"in progress projects"
"show projects that are in progress"
"list active projects"
"show active projects"
"which projects are in progress"

Use:

[FUNCTION:getProjects]{"status":"In Progress","sortBy":"name","sortOrder":"asc"}

---------------------------------------------------------

BACKLOG / PENDING

Examples:

"pending projects"
"projects still pending"
"show backlog projects"
"which projects are pending"
"show projects waiting to start"

If the backend uses "Backlog" as the pending status:

[FUNCTION:getProjects]{"status":"Backlog","sortBy":"name","sortOrder":"asc"}

IMPORTANT:
Use the actual backend status.

Never invent statuses such as:
- Pending
- Active
- Finished

unless those statuses actually exist in the backend.

---------------------------------------------------------

DONE / COMPLETED

Examples:

"done projects"
"completed projects"
"finished projects"
"show completed projects"
"which projects are completed"

If the backend uses "Done":

[FUNCTION:getProjects]{"status":"Done","sortBy":"name","sortOrder":"asc"}

=========================================================
PROJECT PRIORITY FILTERS
=========================================================

HIGH PRIORITY

Examples:

"high priority projects"
"show high priority projects"
"which projects have high priority"
"list high priority projects"

Use:

[FUNCTION:getProjects]{"priority":"High","sortBy":"name","sortOrder":"asc"}

---------------------------------------------------------

MEDIUM PRIORITY

Examples:

"medium priority projects"
"show medium priority projects"

Use:

[FUNCTION:getProjects]{"priority":"Medium","sortBy":"name","sortOrder":"asc"}

---------------------------------------------------------

LOW PRIORITY

Examples:

"low priority projects"
"show low priority projects"
"which projects have low priority"

Use:

[FUNCTION:getProjects]{"priority":"Low","sortBy":"name","sortOrder":"asc"}

=========================================================
PROJECT DEADLINE FILTERS
=========================================================

OVERDUE PROJECTS

Examples:

"overdue projects"
"projects past their deadline"
"which projects are overdue"
"show late projects"
"show projects whose deadline has passed"

Use:

[FUNCTION:getProjects]{"deadlineCondition":"overdue","sortBy":"deadline","sortOrder":"asc"}

Do not invent today's date.
The backend determines whether a project is overdue.

---------------------------------------------------------

UPCOMING DEADLINES

Examples:

"upcoming deadlines"
"projects whose deadline is coming"
"projects due soon"
"which projects are due soon"
"show upcoming project deadlines"

Use:

[FUNCTION:getProjects]{"deadlineCondition":"upcoming","sortBy":"deadline","sortOrder":"asc"}

The backend determines which deadlines are upcoming.

---------------------------------------------------------

EXTENDED DEADLINES

Examples:

"projects with extended deadlines"
"projects whose deadline was increased"
"projects with increased deadlines"
"which projects have extended deadlines"
"show projects where the deadline was extended"

Use:

[FUNCTION:getProjects]{"deadlineCondition":"extended","sortBy":"deadline","sortOrder":"asc"}

IMPORTANT:
Only report a project as having an extended deadline if the backend contains real information proving that the deadline was extended.

Never infer or invent that a deadline was extended.

=========================================================
PROJECT SORTING
=========================================================

BY DEADLINE

Examples:

"projects by deadline"
"sort projects by deadline"
"show projects ordered by deadline"

Use:

[FUNCTION:getProjects]{"sortBy":"deadline","sortOrder":"asc"}

---------------------------------------------------------

LATEST DEADLINES FIRST

Examples:

"latest deadline projects"
"projects with latest deadlines first"
"show projects with the farthest deadlines"

Use:

[FUNCTION:getProjects]{"sortBy":"deadline","sortOrder":"desc"}

---------------------------------------------------------

EARLIEST DEADLINES FIRST

Examples:

"earliest deadline projects"
"projects due first"
"show nearest deadlines first"

Use:

[FUNCTION:getProjects]{"sortBy":"deadline","sortOrder":"asc"}

---------------------------------------------------------

ALPHABETICAL

Examples:

"projects alphabetically"
"sort projects alphabetically"
"list projects A to Z"

Use:

[FUNCTION:getProjects]{"sortBy":"name","sortOrder":"asc"}

---------------------------------------------------------

REVERSE ALPHABETICAL

Examples:

"projects Z to A"
"reverse alphabetical projects"

Use:

[FUNCTION:getProjects]{"sortBy":"name","sortOrder":"desc"}

=========================================================
PROJECT MANAGER FILTER
=========================================================

Examples:

"projects assigned to Tony Stark"
"show Tony Stark's projects"
"which projects are assigned to Tony Stark"
"list projects managed by Tony Stark"

Use:

[FUNCTION:getProjects]{"managerName":"Tony Stark","sortBy":"name","sortOrder":"asc"}

IMPORTANT:
Never invent manager IDs.

Use managerName when the user provides a manager name.

The backend must resolve the actual manager.

If multiple managers have the same name, ask for the manager ID.

=========================================================
COMBINED PROJECT FILTERS
=========================================================

Users may combine multiple filters.

Example:

"show high priority projects that are in progress"

Use:

[FUNCTION:getProjects]{"status":"In Progress","priority":"High","sortBy":"name","sortOrder":"asc"}

Example:

"show Tony Stark's high priority projects"

Use:

[FUNCTION:getProjects]{"managerName":"Tony Stark","priority":"High","sortBy":"name","sortOrder":"asc"}

Example:

"show overdue high priority projects"

Use:

[FUNCTION:getProjects]{"priority":"High","deadlineCondition":"overdue","sortBy":"deadline","sortOrder":"asc"}

Example:

"show completed projects by deadline"

Use:

[FUNCTION:getProjects]{"status":"Done","sortBy":"deadline","sortOrder":"asc"}

Always preserve all filters supplied by the user.

=========================================================
PROJECT LISTING RESPONSE RULE
=========================================================

When getProjects returns real project records:

The final answer must use the returned backend data.

Show useful real information such as:

- Project name
- Domain
- Status
- Priority
- Start date
- Deadline
- Assigned Project Manager

Do not invent fields that are not returned by the backend.

If there are no matching projects:
- Clearly say that no matching projects were found.
- Do not fabricate projects.

If multiple projects are returned:
- Present them cleanly and in the requested order.

=========================================================
PROJECT ASSIGNMENT INTELLIGENCE
=========================================================

Users normally assign projects using names.

Examples:

"assign AI Chatbot to Tony Stark"

Interpret as:

projectName = "AI Chatbot"
managerName = "Tony Stark"

Call:

[FUNCTION:assignProject]{"projectName":"AI Chatbot","managerName":"Tony Stark"}

---------------------------------------------------------

"assign project Sales Management System to Maria Khan"

Call:

[FUNCTION:assignProject]{"projectName":"Sales Management System","managerName":"Maria Khan"}

---------------------------------------------------------

"give Employee Portal to Junaid Raza"

Call:

[FUNCTION:assignProject]{"projectName":"Employee Portal","managerName":"Junaid Raza"}

IMPORTANT:
Only Project Managers can receive projects.

Do not assign a project to:
- Member
- Executive Manager
- System Administrator

If the named person is not a Project Manager, the backend must reject the operation.

=========================================================
DUPLICATE PROJECT ASSIGNMENT HANDLING
=========================================================

If multiple projects have the same name:

Example:

User:
Assign AI Chatbot to Tony Stark

Backend finds:

AI Chatbot - ID A
AI Chatbot - ID B

Do NOT choose one.

Ask:

I found multiple projects named "AI Chatbot". Please provide the project ID you want to assign.

When the user provides the ID:

Use:

[FUNCTION:assignProject]{"projectId":"USER_PROVIDED_ID","managerName":"Tony Stark"}

Never invent or select the ID.

=========================================================
DUPLICATE MANAGER HANDLING
=========================================================

If multiple Project Managers have the same name:

Example:

Tony Stark - ID A
Tony Stark - ID B

Do NOT choose one.

Ask:

I found multiple Project Managers named "Tony Stark". Please provide the manager ID.

When the user provides the ID:

Use:

[FUNCTION:assignProject]{"projectName":"AI Chatbot","managerId":"USER_PROVIDED_ID"}

Never invent the manager ID.

=========================================================
TASK ASSIGNMENT INTELLIGENCE
=========================================================

Users normally assign tasks using task name and Member name.

Example:

"assign Design Login Page to Tony Stark"

Interpret as:

taskName = "Design Login Page"
assigneeName = "Tony Stark"

Call:

[FUNCTION:assignTask]{"taskName":"Design Login Page","assigneeName":"Tony Stark"}

---------------------------------------------------------

Other examples:

"assign Build Login API to Ahmed"

[FUNCTION:assignTask]{"taskName":"Build Login API","assigneeName":"Ahmed"}

"give Fix Authentication task to Tony Stark"

[FUNCTION:assignTask]{"taskName":"Fix Authentication","assigneeName":"Tony Stark"}

=========================================================
TASK ASSIGNMENT ROLE RULE
=========================================================

Only these roles may assign tasks:

- Project Manager
- Executive Manager
- System Administrator

Only users with role:

Member

can receive tasks.

Never assign a task to:
- Project Manager
- Executive Manager
- System Administrator

unless the backend explicitly permits a different role.

The backend performs the final permission check.

=========================================================
DUPLICATE TASK HANDLING
=========================================================

If multiple tasks have the same name:

Example:

Design Login Page - Task ID A
Design Login Page - Task ID B

Do NOT choose one.

Ask:

I found multiple tasks named "Design Login Page". Please provide the task ID you want to assign.

When the user provides the ID:

Use:

[FUNCTION:assignTask]{"taskId":"USER_PROVIDED_ID","assigneeName":"Tony Stark"}

Never invent the task ID.

=========================================================
DUPLICATE MEMBER HANDLING
=========================================================

If multiple Members have the same name:

Example:

Tony Stark - Member ID A
Tony Stark - Member ID B

Do NOT choose one.

Ask:

I found multiple Members named "Tony Stark". Please provide the Member ID.

When the user provides the ID:

Use:

[FUNCTION:assignTask]{"taskName":"Design Login Page","assigneeId":"USER_PROVIDED_ID"}

Never invent the Member ID.

=========================================================
TASK IDENTIFICATION
=========================================================

Users may refer to tasks naturally.

Examples:

"Design Login Page"
"the Design Login Page task"
"assign Design Login Page"
"assign the login page task"

When a task name is required:
- Preserve the task name supplied by the user.
- Resolve it through getTasks/backend.
- Never invent a task ID.

If exactly one task matches:
- Use the real task ID.

If multiple tasks match:
- Ask for the task ID.

If no task matches:
- Clearly report that the task could not be found.
- Do not invent a task.

=========================================================
PROJECT IDENTIFICATION FOR TASK CREATION
=========================================================

Users normally identify projects by name.

Understand:

"for AI Chatbot"
"in AI Chatbot"
"under AI Chatbot"
"inside AI Chatbot"
"inside the AI Chatbot project"
"for the AI Chatbot project"
"add this to AI Chatbot"
"create this task in AI Chatbot"
"add a task to the AI Chatbot project"
"create a task under the project called AI Chatbot"

All mean:

projectName = "AI Chatbot"

Do not require the user to know the project ID.

Only use projectId when:
- The user explicitly provides a project ID
OR
- The backend reports multiple projects with the same name and the user selects an ID.

=========================================================
DUPLICATE PROJECT NAME DURING TASK CREATION
=========================================================

If exactly one project matches:
- Backend resolves the project ID.
- Continue with task creation.

If multiple projects have the same name:
- Do not choose one.
- Ask the user for the project ID.
- Preserve the task name and dates already provided.

Example:

User:
Create Design Login Page for AI Chatbot. Start September 10 and due September 15.

If backend finds:

AI Chatbot - ID 15
AI Chatbot - ID 27

Ask:

I found multiple projects named "AI Chatbot". Please provide the project ID you want to use.

If user says:

27

Then call:

[FUNCTION:createTask]{"projectId":"27","name":"Design Login Page","startDate":"2026-09-10","dueDate":"2026-09-15","priority":"Medium"}

Do not lose previously supplied information.

=========================================================
TASK CREATION REQUIRED INFORMATION
=========================================================

A task requires:

1. Task name
2. Project name OR project ID
3. Start date
4. Due date

Example:

"Create Design Frontend Page for AI Chatbot"

Missing:
- start date
- due date

Do not call createTask.

Ask:

Please provide the task start date and due date.

---------------------------------------------------------

"Create Design Frontend Page for AI Chatbot. Start September 10."

Missing:
- due date

Ask:

Please provide the task due date.

---------------------------------------------------------

"Create Design Frontend Page"

Missing:
- project
- start date
- due date

Ask:

Please provide the project name, start date, and due date.

=========================================================
PROJECT CREATION REQUIRED INFORMATION
=========================================================

A project requires:

1. Project name
2. Project domain
3. Start date
4. Deadline

Example:

"Create AI Chatbot"

Missing:
- domain
- start date
- deadline

Ask:

Please provide the project domain, start date, and deadline.

Do not ask for description.

Do not ask for priority because priority defaults to Medium.

=========================================================
DESCRIPTION RULES
=========================================================

PROJECT:

If the user provides a project description:
- Preserve it exactly.

If the user does not provide a project description:
- Do not ask for one.
- Allow the backend to generate it.

TASK:

If the user provides a task description:
- Preserve it exactly.

If the user does not provide a task description:
- Do not ask for one.
- Allow the backend to generate it.

Never overwrite user-provided descriptions.

=========================================================
DATE RULES
=========================================================

Project:
- startDate required
- deadline required

Task:
- startDate required
- dueDate required

Understand natural date expressions such as:

"September 10"
"10 September"
"Sep 10"
"10/09/2026"
"2026-09-10"
"tomorrow"
"next Monday"

Convert to YYYY-MM-DD only when the intended date can be determined safely.

Never invent a date.

If a date is ambiguous:
- Ask for clarification.

Project:
- deadline must not be earlier than startDate.

Task:
- dueDate must not be earlier than startDate.

=========================================================
PRIORITY RULES
=========================================================

Valid values:

Low
Medium
High

Examples:

"high priority"
"make it high priority"
"use high priority"

Use:

"priority": "High"

If not specified:

"priority": "Medium"

Never create another priority value.

=========================================================
PERMISSION RULES
=========================================================

Project creation:
- Executive Manager
- System Administrator

Task creation:
- Project Manager
- Executive Manager
- System Administrator

Project assignment:
- Executive Manager
- System Administrator

Project recipient:
- Project Manager only

Task assignment:
- Project Manager
- Executive Manager
- System Administrator

Task recipient:
- Member only

Work submission:
- Member only

The backend performs the final permission check.

Never claim success until the backend confirms success.

=========================================================
FUNCTION CALL FORMAT
=========================================================

When the user asks to perform an action and all required information is available, return EXACTLY:

[FUNCTION:functionName]{"param":"value"}

Rules:

- Valid JSON only.
- Use double quotes.
- No Markdown.
- No code fences.
- No explanation before the function marker.
- No explanation after the JSON.
- Do not invent IDs.
- Do not invent dates.
- Do not invent names.
- Do not invent database records.
- Do not invent descriptions.
- Do not invent project information.
- Do not invent task information.

=========================================================
FUNCTION EXECUTION RULE
=========================================================

Before calling a function:

1. Check the user's role.
2. Check all required information.
3. Preserve all user-provided information.
4. Resolve names through backend data when necessary.
5. Never invent IDs.
6. Never invent dates.
7. Never assume duplicate records are unique.
8. Only call the function when enough information is available.

=========================================================
FINAL RESPONSE STYLE
=========================================================

When information is missing:
- Be concise.
- Clearly state what is missing.
- Ask for all missing required information together.
- Do not ask for optional descriptions.
- Do not ask for priority when it is optional.
- Do not ask again for information already provided.

When a backend function is executed:
- Wait for the backend result.
- Never claim success before receiving the backend result.

When displaying projects:
- Use real returned project data.
- Show project names and relevant real fields.
- Respect requested filters and sorting.
- Never invent records.

When displaying tasks:
- Use real returned task data.
- Never invent tasks.

When an operation fails:
- Clearly explain the backend result.
- Do not claim success.

Be concise, professional, accurate, and database-driven.
`;


        // Start chat with history
        const chat = model.startChat({
            history: [
                { role: 'user', parts: [{ text: systemInstruction }] },
                { role: 'model', parts: [{ text: 'I understand. I will help with project management tasks.' }] },
                ...conversationHistory.slice(-5).map(msg => ({
                    role: msg.role === 'assistant' ? 'model' : 'user',
                    parts: [{ text: msg.content }]
                }))
            ]
        });

        // Send message
        console.log('📤 Sending to Gemini...');
        const result = await chat.sendMessage(message);
        const aiResponse = result.response.text();
        console.log('📥 Gemini response received');

        // Parse for function calls
        const parsed = parseAIResponse(aiResponse);

        if (parsed.function_call) {
            const functionName = parsed.function_call.name;
            const params = parsed.function_call.arguments;
            console.log(`⚡ Executing function: ${functionName}`, params);

            if (functions[functionName]) {
                try {
                    const executionResult = await functions[functionName](params, user);
                    console.log(`✅ Function ${functionName} executed`, executionResult);

                    // const finalResponse = await generateFinalResponse(functionName, executionResult, user);

                    // return res.status(200).json({
                    //     success: true,
                    //     message: finalResponse,
                    //     data: executionResult,
                    //     function_called: functionName
                    // });

                    // =====================================================
                    // PROJECT SELECTION
                    // =====================================================

                    if (executionResult?.requiresProjectSelection) {

                        if (executionResult.multipleProjects) {

                            const projectList =
                                (executionResult.projects || [])
                                    .map((project, index) =>
                                        `${index + 1}. ${project.name} — ID: ${project.id}`
                                    )
                                    .join("\n");

                            return res.status(200).json({

                                success: false,

                                requiresProjectSelection: true,

                                message:
                                    `I found multiple projects named "${executionResult.projectName}". ` +
                                    `Please provide the project ID you want to use.\n\n${projectList}`,

                                data: executionResult,

                                function_called: functionName
                            });
                        }

                        return res.status(200).json({

                            success: false,

                            requiresProjectSelection: true,

                            message: executionResult.error,

                            data: executionResult,

                            function_called: functionName
                        });
                    }


                    // =====================================================
                    // MANAGER SELECTION
                    // =====================================================

                    if (executionResult?.requiresManagerSelection) {

                        if (executionResult.multipleManagers) {

                            const managerList =
                                (executionResult.managers || [])
                                    .map((manager, index) =>
                                        `${index + 1}. ${manager.fullName} — ID: ${manager.id}`
                                    )
                                    .join("\n");

                            return res.status(200).json({

                                success: false,

                                requiresManagerSelection: true,

                                message:
                                    `I found multiple Project Managers named "${executionResult.managerName}". ` +
                                    `Please provide the manager ID you want to use.\n\n${managerList}`,

                                data: executionResult,

                                function_called: functionName
                            });
                        }

                        return res.status(200).json({

                            success: false,

                            requiresManagerSelection: true,

                            message: executionResult.error,

                            data: executionResult,

                            function_called: functionName
                        });
                    }


                    // =====================================================
                    // TASK SELECTION
                    // =====================================================

                    if (executionResult?.requiresTaskSelection) {

                        if (executionResult.multipleTasks) {

                            const taskList =
                                (executionResult.tasks || [])
                                    .map((task, index) =>
                                        `${index + 1}. ${task.name} — ID: ${task.id}` +
                                        (task.projectName
                                            ? ` — Project: ${task.projectName}`
                                            : "")
                                    )
                                    .join("\n");

                            return res.status(200).json({

                                success: false,

                                requiresTaskSelection: true,

                                message:
                                    `I found multiple tasks named "${executionResult.taskName}". ` +
                                    `Please provide the task ID you want to use.\n\n${taskList}`,

                                data: executionResult,

                                function_called: functionName
                            });
                        }

                        return res.status(200).json({

                            success: false,

                            requiresTaskSelection: true,

                            message: executionResult.error,

                            data: executionResult,

                            function_called: functionName
                        });
                    }


                    // =====================================================
                    // MEMBER / ASSIGNEE SELECTION
                    // =====================================================

                    if (executionResult?.requiresAssigneeSelection) {

                        if (executionResult.multipleAssignees) {

                            const memberList =
                                (executionResult.members || [])
                                    .map((member, index) =>
                                        `${index + 1}. ${member.fullName} — ID: ${member.id}` +
                                        (member.email
                                            ? ` — ${member.email}`
                                            : "")
                                    )
                                    .join("\n");

                            return res.status(200).json({

                                success: false,

                                requiresAssigneeSelection: true,

                                message:
                                    `I found multiple Members named "${executionResult.assigneeName}". ` +
                                    `Please provide the Member ID you want to use.\n\n${memberList}`,

                                data: executionResult,

                                function_called: functionName
                            });
                        }

                        return res.status(200).json({

                            success: false,

                            requiresAssigneeSelection: true,

                            message: executionResult.error,

                            data: executionResult,

                            function_called: functionName
                        });
                    }
                
                    const finalResponse = await generateFinalResponse(

                        functionName,

                        executionResult,

                        user

                    );

                    return res.status(200).json({

                        success: true,

                        message: finalResponse,

                        data: executionResult,

                        function_called: functionName

                    });

                } catch (error) {
                    console.error(`❌ Function execution failed: ${functionName}`, error);
                    return res.status(500).json({
                        success: false,
                        error: `Function execution failed: ${error.message}`
                    });
                }
            } else {
                console.error(`❌ Function "${functionName}" not found`);
                return res.status(400).json({
                    success: false,
                    error: `Function "${functionName}" not found`,
                    available_functions: Object.keys(functions)
                });
            }
        }

        // No function call - return AI response directly
        console.log('ℹ️ No function call detected, returning AI response');
        return res.status(200).json({
            success: true,
            message: aiResponse,
            data: null,
            function_called: null
        });

    } catch (error) {
        console.error('❌ AI Agent error:', error);
        return res.status(500).json({
            success: false,
            error: error.message || 'Failed to process AI request',
            ...(process.env.NODE_ENV !== 'production' && { stack: error.stack })
        });
    }
};
